#!/bin/bash
RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
DIM='\033[2m'
RESET='\033[0m'

CYBERTUZ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [ -z "$CYBERTUZ_LANG" ]; then
    source "$CYBERTUZ_DIR/lang.sh"
    ct_load_lang || _ct_set_lang "en"
fi

pause_modul() {
    echo ""
    echo -ne "${DIM}  $CT_ENTER${RESET}"
    read -r
}

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
DIM='\033[2m'
RESET='\033[0m'

pause_modul() {
    echo ""
    echo -e "${DIM}Tekan ENTER untuk melanjutkan...${RESET}"
    read -r
}

menu_jaringan() {
    while true; do
        clear
        echo -e "${RED}=== $CT_MOD_HDR_2 ===${RESET}"
        echo ""
        echo -e "  ${GREEN}[1]${RESET}  $CT_M2_1"
        echo -e "  ${GREEN}[2]${RESET}  $CT_M2_2"
        echo -e "  ${GREEN}[3]${RESET}  $CT_M2_3"
        echo -e "  ${GREEN}[4]${RESET}  $CT_M2_4"
        echo -e "  ${GREEN}[5]${RESET}  $CT_M2_5"
        echo -e "  ${GREEN}[6]${RESET}  $CT_M2_6"
        echo -e "  ${GREEN}[7]${RESET}  $CT_M2_7"
        echo -e "  ${GREEN}[8]${RESET}  $CT_M2_8"
        echo -e "  ${GREEN}[9]${RESET}  $CT_M2_9"
        echo -e "  ${RED}[0]${RESET}  $CT_BACK"
        echo ""
        echo -ne "  ${CYAN}$CT_MPROMPT${RESET}"
        read -r choice
        case $choice in
            1) belajar_osi ;;
            2) belajar_ip ;;
            3) belajar_protokol ;;
            4) belajar_dns ;;
            5) belajar_http ;;
            6) belajar_firewall ;;
            7) simulasi_packet ;;
            8) simulasi_jaringan ;;
            9) lab_koneksi_lokal ;;
            0) return ;;
            *) echo -e "${RED}$CT_INVALID${RESET}"; sleep 1 ;;
        esac
    done
}

belajar_osi() {
    clear
    echo -e "${YELLOW}=== MODEL OSI DAN TCP/IP ===${RESET}"
    echo ""
    echo "Model OSI (Open Systems Interconnection) adalah framework 7 layer"
    echo "yang menjelaskan bagaimana komunikasi jaringan bekerja."
    echo ""
    echo -e "${WHITE}7 LAYER OSI (dari atas ke bawah):${RESET}"
    echo ""
    echo -e "  ${RED}Layer 7 - Application${RESET}"
    echo "  Interaksi langsung dengan aplikasi pengguna"
    echo "  Protokol: HTTP, HTTPS, FTP, SMTP, DNS, SSH, Telnet"
    echo "  Contoh: Browser web, email client"
    echo ""
    echo -e "  ${RED}Layer 6 - Presentation${RESET}"
    echo "  Translasi, enkripsi, dan kompresi data"
    echo "  Format: JPEG, PNG, MP3, SSL/TLS, ASCII, EBCDIC"
    echo "  Contoh: SSL handshake, data encoding"
    echo ""
    echo -e "  ${RED}Layer 5 - Session${RESET}"
    echo "  Membuat, mengelola, dan mengakhiri sesi komunikasi"
    echo "  Protokol: NetBIOS, PPTP, SAP, L2TP"
    echo "  Contoh: Login session, streaming session"
    echo ""
    echo -e "  ${YELLOW}Layer 4 - Transport${RESET}"
    echo "  End-to-end communication, flow control, error recovery"
    echo "  Protokol: TCP (reliable), UDP (unreliable)"
    echo "  TCP: Three-way handshake (SYN, SYN-ACK, ACK)"
    echo ""
    echo -e "  ${YELLOW}Layer 3 - Network${RESET}"
    echo "  Routing paket antar jaringan yang berbeda"
    echo "  Protokol: IP, ICMP, OSPF, BGP, RIP"
    echo "  Perangkat: Router"
    echo ""
    echo -e "  ${GREEN}Layer 2 - Data Link${RESET}"
    echo "  Transfer data yang reliable dalam satu segmen jaringan"
    echo "  Protokol: Ethernet, Wi-Fi (802.11), ARP, PPP"
    echo "  Perangkat: Switch, Bridge"
    echo "  Addressing: MAC Address"
    echo ""
    echo -e "  ${GREEN}Layer 1 - Physical${RESET}"
    echo "  Transmisi bit mentah melalui medium fisik"
    echo "  Medium: Kabel ethernet, fiber optik, sinyal radio"
    echo "  Perangkat: Hub, kabel, wireless adapter"
    echo ""
    echo -e "${WHITE}TCP/IP MODEL (4 Layer):${RESET}"
    echo ""
    echo "  Application Layer  = OSI Layer 5, 6, 7"
    echo "  Transport Layer    = OSI Layer 4"
    echo "  Internet Layer     = OSI Layer 3"
    echo "  Network Access     = OSI Layer 1, 2"
    echo ""
    echo -e "${WHITE}TCP THREE-WAY HANDSHAKE:${RESET}"
    echo ""
    echo "  Client                     Server"
    echo "    |------- SYN ----------->|   (Client ingin koneksi)"
    echo "    |<------ SYN-ACK --------|   (Server setuju)"
    echo "    |------- ACK ----------->|   (Konfirmasi, koneksi terbuka)"
    echo "    |====== DATA EXCHANGE ===|"
    echo "    |------- FIN ----------->|   (Client tutup koneksi)"
    echo "    |<------ ACK ------------|"
    echo "    |<------ FIN ------------|   (Server tutup koneksi)"
    echo "    |------- ACK ----------->|"
    pause_modul
}

belajar_ip() {
    clear
    echo -e "${YELLOW}=== IP ADDRESS, SUBNET, DAN CIDR ===${RESET}"
    echo ""
    echo -e "${WHITE}IPv4 ADDRESS:${RESET}"
    echo "Terdiri dari 32 bit, ditulis dalam 4 oktet desimal"
    echo "Contoh: 192.168.1.100"
    echo "Range: 0.0.0.0 hingga 255.255.255.255"
    echo ""
    echo -e "${WHITE}KELAS IP ADDRESS:${RESET}"
    echo ""
    echo "  Kelas A: 1.0.0.0 - 126.255.255.255 (subnet /8)"
    echo "           Untuk jaringan sangat besar"
    echo ""
    echo "  Kelas B: 128.0.0.0 - 191.255.255.255 (subnet /16)"
    echo "           Untuk jaringan menengah"
    echo ""
    echo "  Kelas C: 192.0.0.0 - 223.255.255.255 (subnet /24)"
    echo "           Untuk jaringan kecil"
    echo ""
    echo "  Kelas D: 224.0.0.0 - 239.255.255.255 (Multicast)"
    echo "  Kelas E: 240.0.0.0 - 255.255.255.255 (Reserved)"
    echo ""
    echo -e "${WHITE}PRIVATE IP RANGES:${RESET}"
    echo "  10.0.0.0/8      (Class A private)"
    echo "  172.16.0.0/12   (Class B private)"
    echo "  192.168.0.0/16  (Class C private)"
    echo "  127.0.0.0/8     (Loopback)"
    echo ""
    echo -e "${WHITE}SUBNET MASK:${RESET}"
    echo "  /8  = 255.0.0.0      = 16.777.214 host"
    echo "  /16 = 255.255.0.0    = 65.534 host"
    echo "  /24 = 255.255.255.0  = 254 host"
    echo "  /25 = 255.255.255.128 = 126 host"
    echo "  /26 = 255.255.255.192 = 62 host"
    echo "  /27 = 255.255.255.224 = 30 host"
    echo "  /28 = 255.255.255.240 = 14 host"
    echo "  /29 = 255.255.255.248 = 6 host"
    echo "  /30 = 255.255.255.252 = 2 host"
    echo ""
    echo -e "${WHITE}PERHITUNGAN SUBNET:${RESET}"
    echo "  Contoh: 192.168.1.0/24"
    echo "  Network Address : 192.168.1.0"
    echo "  Broadcast       : 192.168.1.255"
    echo "  Usable Range    : 192.168.1.1 - 192.168.1.254"
    echo "  Total Host      : 254"
    echo ""
    echo -e "${WHITE}IPv6 (sekilas):${RESET}"
    echo "  128 bit, ditulis dalam 8 grup hexadecimal"
    echo "  Contoh: 2001:0db8:85a3:0000:0000:8a2e:0370:7334"
    echo "  Disingkat: 2001:db8:85a3::8a2e:370:7334"
    echo ""
    echo -e "${WHITE}SIMULASI SUBNET CALCULATOR:${RESET}"
    echo -ne "  Masukkan IP/CIDR (misal 192.168.1.0/24): "
    read -r ip_cidr
    if [[ "$ip_cidr" =~ ^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)/([0-9]+)$ ]]; then
        local ip="${BASH_REMATCH[1]}"
        local cidr="${BASH_REMATCH[2]}"
        local hosts=$((2 ** (32 - cidr) - 2))
        echo ""
        echo "  IP       : $ip"
        echo "  CIDR     : /$cidr"
        echo "  Jumlah Host: $hosts"
    else
        echo "  $CT_INVALID - Format: X.X.X.X/XX"
    fi
    pause_modul
}

belajar_protokol() {
    clear
    echo -e "${YELLOW}=== PROTOKOL JARINGAN PENTING ===${RESET}"
    echo ""
    echo -e "${WHITE}PROTOKOL BERDASARKAN PORT:${RESET}"
    echo ""
    printf "  %-8s %-8s %-40s\n" "PORT" "PROTO" "LAYANAN"
    echo "  ----------------------------------------------------------------"
    printf "  %-8s %-8s %-40s\n" "20,21" "TCP" "FTP (File Transfer Protocol)"
    printf "  %-8s %-8s %-40s\n" "22" "TCP" "SSH (Secure Shell)"
    printf "  %-8s %-8s %-40s\n" "23" "TCP" "Telnet (TIDAK AMAN)"
    printf "  %-8s %-8s %-40s\n" "25" "TCP" "SMTP (Email keluar)"
    printf "  %-8s %-8s %-40s\n" "53" "UDP/TCP" "DNS (Domain Name System)"
    printf "  %-8s %-8s %-40s\n" "67,68" "UDP" "DHCP"
    printf "  %-8s %-8s %-40s\n" "80" "TCP" "HTTP (Web tidak terenkripsi)"
    printf "  %-8s %-8s %-40s\n" "110" "TCP" "POP3 (Email masuk)"
    printf "  %-8s %-8s %-40s\n" "143" "TCP" "IMAP (Email masuk)"
    printf "  %-8s %-8s %-40s\n" "443" "TCP" "HTTPS (Web terenkripsi)"
    printf "  %-8s %-8s %-40s\n" "445" "TCP" "SMB (File sharing Windows)"
    printf "  %-8s %-8s %-40s\n" "3306" "TCP" "MySQL Database"
    printf "  %-8s %-8s %-40s\n" "3389" "TCP" "RDP (Remote Desktop)"
    printf "  %-8s %-8s %-40s\n" "5432" "TCP" "PostgreSQL Database"
    printf "  %-8s %-8s %-40s\n" "6379" "TCP" "Redis"
    printf "  %-8s %-8s %-40s\n" "8080" "TCP" "HTTP Alternate"
    printf "  %-8s %-8s %-40s\n" "27017" "TCP" "MongoDB"
    echo ""
    echo -e "${WHITE}PROTOKOL BERBAHAYA YANG PERLU DIWASPADAI:${RESET}"
    echo ""
    echo "  Telnet (port 23)"
    echo "  - Mengirim data dalam plaintext termasuk password"
    echo "  - Harus diganti dengan SSH"
    echo ""
    echo "  FTP (port 21)"
    echo "  - Login credential tidak terenkripsi"
    echo "  - Gunakan SFTP atau FTPS sebagai gantinya"
    echo ""
    echo "  HTTP (port 80)"
    echo "  - Semua komunikasi bisa disadap"
    echo "  - Gunakan HTTPS (port 443)"
    echo ""
    echo "  SNMPv1/v2 (port 161)"
    echo "  - Community string dikirim plaintext"
    echo "  - Gunakan SNMPv3 dengan enkripsi"
    pause_modul
}

belajar_dns() {
    clear
    echo -e "${YELLOW}=== DNS DAN CARA KERJANYA ===${RESET}"
    echo ""
    echo -e "${WHITE}APA ITU DNS?${RESET}"
    echo "Domain Name System adalah sistem yang menerjemahkan nama domain"
    echo "yang mudah diingat manusia (google.com) menjadi alamat IP"
    echo "yang dipahami komputer (142.250.185.78)"
    echo ""
    echo -e "${WHITE}HIERARKI DNS:${RESET}"
    echo ""
    echo "  . (Root DNS)"
    echo "  |"
    echo "  +-- .com (TLD - Top Level Domain)"
    echo "  |     |"
    echo "  |     +-- google.com (SLD - Second Level Domain)"
    echo "  |           |"
    echo "  |           +-- www.google.com (Subdomain)"
    echo "  |           +-- mail.google.com"
    echo "  |"
    echo "  +-- .id"
    echo "  +-- .org"
    echo "  +-- .net"
    echo ""
    echo -e "${WHITE}PROSES DNS RESOLUTION:${RESET}"
    echo ""
    echo "  1. Browser ketik www.example.com"
    echo "  2. Cek cache lokal di /etc/hosts dan browser cache"
    echo "  3. Query ke DNS Resolver (biasanya ISP atau 8.8.8.8)"
    echo "  4. Resolver query Root DNS Server"
    echo "  5. Root Server arahkan ke .com TLD Server"
    echo "  6. TLD Server arahkan ke example.com Authoritative Server"
    echo "  7. Authoritative Server kembalikan IP address"
    echo "  8. Browser koneksi ke IP tersebut"
    echo ""
    echo -e "${WHITE}TIPE RECORD DNS:${RESET}"
    echo ""
    echo "  A     : Menunjuk domain ke IPv4 address"
    echo "  AAAA  : Menunjuk domain ke IPv6 address"
    echo "  CNAME : Alias, menunjuk ke domain lain"
    echo "  MX    : Mail server untuk domain"
    echo "  NS    : Name server untuk domain"
    echo "  TXT   : Data teks (SPF, DKIM, verifikasi)"
    echo "  PTR   : Reverse DNS (IP ke domain)"
    echo "  SOA   : Start of Authority"
    echo ""
    echo -e "${WHITE}DNS DALAM KONTEKS KEAMANAN:${RESET}"
    echo ""
    echo "  DNS Spoofing/Poisoning"
    echo "  - Memasukkan record palsu ke DNS cache"
    echo "  - Mengarahkan user ke website berbahaya"
    echo ""
    echo "  DNS Tunneling"
    echo "  - Menyembunyikan data dalam DNS query"
    echo "  - Digunakan untuk C2 (Command and Control)"
    echo ""
    echo "  DNS Amplification"
    echo "  - Serangan DDoS menggunakan DNS server"
    echo "  - Mengirim query kecil, balasan besar ke korban"
    echo ""
    echo "  DNSSEC"
    echo "  - Ekstensi keamanan DNS"
    echo "  - Memastikan integritas DNS response"
    echo ""
    echo -e "${WHITE}PRAKTIK - Query DNS Lokal:${RESET}"
    echo ""
    if command -v nslookup &>/dev/null; then
        echo "  Menjalankan: nslookup google.com 8.8.8.8"
        timeout 5 nslookup google.com 8.8.8.8 2>/dev/null || echo "  (Tidak bisa konek - mode offline)"
    else
        echo "  nslookup tidak terinstall"
        echo "  Install dengan: pkg install dnsutils"
    fi
    pause_modul
}

belajar_http() {
    clear
    echo -e "${YELLOW}=== HTTP DAN HTTPS ===${RESET}"
    echo ""
    echo -e "${WHITE}HTTP (HyperText Transfer Protocol)${RESET}"
    echo "Protokol komunikasi untuk transfer data di web"
    echo "Port: 80"
    echo "TIDAK terenkripsi - semua data bisa dibaca"
    echo ""
    echo -e "${WHITE}HTTP REQUEST METHODS:${RESET}"
    echo ""
    echo "  GET     : Mengambil resource dari server"
    echo "  POST    : Mengirim data ke server"
    echo "  PUT     : Update seluruh resource"
    echo "  PATCH   : Update sebagian resource"
    echo "  DELETE  : Hapus resource"
    echo "  HEAD    : Sama seperti GET tapi tanpa body"
    echo "  OPTIONS : Cek method yang didukung"
    echo ""
    echo -e "${WHITE}HTTP STATUS CODES:${RESET}"
    echo ""
    echo "  2xx - Sukses"
    echo "    200 OK              : Request berhasil"
    echo "    201 Created         : Resource berhasil dibuat"
    echo "    204 No Content      : Berhasil, tidak ada konten"
    echo ""
    echo "  3xx - Redirect"
    echo "    301 Moved Permanently: URL berubah permanen"
    echo "    302 Found           : Redirect sementara"
    echo ""
    echo "  4xx - Error Client"
    echo "    400 Bad Request     : Request tidak valid"
    echo "    401 Unauthorized    : Perlu autentikasi"
    echo "    403 Forbidden       : Tidak punya izin"
    echo "    404 Not Found       : Resource tidak ditemukan"
    echo "    405 Method Not Allowed: Method tidak diizinkan"
    echo ""
    echo "  5xx - Error Server"
    echo "    500 Internal Server Error: Error di server"
    echo "    502 Bad Gateway     : Proxy error"
    echo "    503 Service Unavailable: Server overload"
    echo ""
    echo -e "${WHITE}HTTP HEADERS PENTING:${RESET}"
    echo ""
    echo "  Request Headers:"
    echo "  User-Agent     : Identitas browser/client"
    echo "  Cookie         : Data session"
    echo "  Authorization  : Token autentikasi"
    echo "  Content-Type   : Jenis data yang dikirim"
    echo "  Referer        : URL sebelumnya"
    echo ""
    echo "  Response Headers:"
    echo "  Set-Cookie     : Menyimpan cookie di browser"
    echo "  Content-Type   : Jenis konten response"
    echo "  X-Frame-Options: Mencegah clickjacking"
    echo "  HSTS           : Memaksa HTTPS"
    echo ""
    echo -e "${WHITE}HTTPS (HTTP Secure):${RESET}"
    echo "HTTP + TLS (Transport Layer Security)"
    echo "Port: 443"
    echo "Mengenkripsi semua komunikasi"
    echo ""
    echo "Proses TLS Handshake:"
    echo "  1. Client Hello (versi TLS, cipher suites)"
    echo "  2. Server Hello (pilih cipher, kirim sertifikat)"
    echo "  3. Client verifikasi sertifikat"
    echo "  4. Key exchange (buat session key)"
    echo "  5. Komunikasi terenkripsi dimulai"
    echo ""
    echo -e "${WHITE}SIMULASI HTTP REQUEST:${RESET}"
    echo ""
    echo "  Contoh GET request ke httpbin.org/get:"
    echo "  curl -v http://httpbin.org/get (akan terlihat header)"
    echo ""
    echo "  Struktur HTTP Request:"
    echo "  GET /index.html HTTP/1.1"
    echo "  Host: www.example.com"
    echo "  User-Agent: Mozilla/5.0"
    echo "  Accept: text/html"
    echo "  Connection: keep-alive"
    echo "  [BLANK LINE]"
    pause_modul
}

belajar_firewall() {
    clear
    echo -e "${YELLOW}=== FIREWALL DAN FILTERING ===${RESET}"
    echo ""
    echo -e "${WHITE}APA ITU FIREWALL?${RESET}"
    echo "Firewall adalah sistem keamanan yang memantau dan mengontrol"
    echo "lalu lintas jaringan berdasarkan aturan keamanan yang ditentukan."
    echo ""
    echo -e "${WHITE}JENIS FIREWALL:${RESET}"
    echo ""
    echo -e "  ${CYAN}1. Packet Filter Firewall${RESET}"
    echo "  Memeriksa header paket (IP, port, protokol)"
    echo "  Generasi pertama, cepat tapi terbatas"
    echo "  Contoh: iptables (Linux)"
    echo ""
    echo -e "  ${CYAN}2. Stateful Inspection Firewall${RESET}"
    echo "  Memantau state koneksi (tracking TCP sessions)"
    echo "  Lebih aman dari packet filter biasa"
    echo ""
    echo -e "  ${CYAN}3. Application Layer Firewall (WAF)${RESET}"
    echo "  Memeriksa payload aplikasi (HTTP, DNS, dll)"
    echo "  Dapat mendeteksi SQL Injection, XSS"
    echo "  Contoh: ModSecurity, AWS WAF"
    echo ""
    echo -e "  ${CYAN}4. Next-Generation Firewall (NGFW)${RESET}"
    echo "  Kombinasi semua jenis di atas"
    echo "  Tambahan: IDS/IPS, SSL inspection, DPI"
    echo "  Contoh: Palo Alto, Fortinet, Cisco Firepower"
    echo ""
    echo -e "${WHITE}ATURAN FIREWALL (Rules):${RESET}"
    echo ""
    echo "  Setiap rule memiliki:"
    echo "  - Source IP / network"
    echo "  - Destination IP / network"
    echo "  - Port / protokol"
    echo "  - Action: ALLOW atau DENY"
    echo ""
    echo "  Contoh iptables rules:"
    echo "  iptables -A INPUT -p tcp --dport 22 -j ACCEPT"
    echo "  iptables -A INPUT -p tcp --dport 80 -j ACCEPT"
    echo "  iptables -A INPUT -p tcp --dport 443 -j ACCEPT"
    echo "  iptables -A INPUT -j DROP   (default deny)"
    echo ""
    echo -e "${WHITE}KONSEP FIREWALL:${RESET}"
    echo ""
    echo "  Default Deny vs Default Allow"
    echo "  - Default Deny (lebih aman): Blok semua, izinkan yang perlu"
    echo "  - Default Allow: Izinkan semua, blok yang berbahaya"
    echo ""
    echo "  Ingress vs Egress Filtering"
    echo "  - Ingress: Filter traffic masuk ke jaringan"
    echo "  - Egress: Filter traffic keluar dari jaringan"
    echo ""
    echo "  Firewall Bypass Techniques:"
    echo "  - Port tunneling (SSH tunneling)"
    echo "  - Protocol manipulation"
    echo "  - Fragmentation attacks"
    echo "  - VPN / proxy"
    pause_modul
}

simulasi_packet() {
    clear
    echo -e "${YELLOW}=== SIMULASI ANALISIS PAKET JARINGAN ===${RESET}"
    echo ""
    echo "Simulasi ini mensimulasikan cara kerja packet analyzer seperti Wireshark"
    echo ""
    echo -e "${WHITE}STRUKTUR PAKET ETHERNET:${RESET}"
    echo ""
    echo "  +------------------+------------------+------+----------+-----+"
    echo "  | Destination MAC  | Source MAC       | Type | Payload  | FCS |"
    echo "  | 6 bytes          | 6 bytes          | 2 B  | 46-1500B | 4 B |"
    echo "  +------------------+------------------+------+----------+-----+"
    echo ""
    echo -e "${WHITE}CONTOH PAKET HTTP (simulasi):${RESET}"
    echo ""
    echo "  === PACKET #1 [TCP SYN] ==="
    echo "  Timestamp : $(date '+%H:%M:%S.%N' | cut -c1-12)"
    echo "  Source    : 192.168.1.100:54231"
    echo "  Dest      : 93.184.216.34:80"
    echo "  Protocol  : TCP"
    echo "  Flags     : SYN"
    echo "  Seq       : 0"
    echo "  Data      : [NONE]"
    echo ""
    echo "  === PACKET #2 [TCP SYN-ACK] ==="
    echo "  Timestamp : $(date '+%H:%M:%S.%N' | cut -c1-12)"
    echo "  Source    : 93.184.216.34:80"
    echo "  Dest      : 192.168.1.100:54231"
    echo "  Protocol  : TCP"
    echo "  Flags     : SYN, ACK"
    echo "  Seq       : 0, Ack: 1"
    echo ""
    echo "  === PACKET #3 [HTTP GET] ==="
    echo "  Timestamp : $(date '+%H:%M:%S.%N' | cut -c1-12)"
    echo "  Source    : 192.168.1.100:54231"
    echo "  Dest      : 93.184.216.34:80"
    echo "  Protocol  : HTTP"
    echo "  Flags     : ACK, PSH"
    echo "  Data      : GET / HTTP/1.1"
    echo "              Host: example.com"
    echo "              User-Agent: Mozilla/5.0"
    echo ""
    echo "  === PACKET #4 [HTTP Response] ==="
    echo "  Source    : 93.184.216.34:80"
    echo "  Protocol  : HTTP"
    echo "  Status    : HTTP/1.1 200 OK"
    echo "  Data      : <html>...</html>"
    echo ""
    echo -e "${WHITE}BAHAYA PLAINTEXT HTTP:${RESET}"
    echo ""
    echo "  Jika menggunakan HTTP (bukan HTTPS), penyerang yang"
    echo "  berada di jaringan yang sama bisa melihat:"
    echo "  - Username dan password login"
    echo "  - Cookie session"
    echo "  - Data formulir yang dikirim"
    echo "  - Semua konten yang dibrowse"
    echo ""
    echo "  Dengan Wireshark atau tcpdump, ini semua terlihat jelas!"
    echo ""
    echo -e "${WHITE}CARA MELINDUNGI:${RESET}"
    echo "  - Selalu gunakan HTTPS"
    echo "  - VPN saat di Wi-Fi publik"
    echo "  - Jangan masukkan data sensitif di HTTP"
    pause_modul
}

simulasi_jaringan() {
    clear
    echo -e "${YELLOW}=== SIMULASI JARINGAN INTERAKTIF ===${RESET}"
    echo ""
    echo "Kita akan simulasikan sebuah jaringan perusahaan kecil"
    echo ""
    echo -e "${WHITE}TOPOLOGI JARINGAN:${RESET}"
    echo ""
    echo "  Internet (0.0.0.0/0)"
    echo "       |"
    echo "   [ISP Router]"
    echo "       | 203.0.113.1"
    echo "   [Firewall/Router] 203.0.113.2"
    echo "       |"
    echo "   +---+---+"
    echo "   |       |"
    echo " [DMZ]  [LAN]"
    echo " /24     /24"
    echo " |       |"
    echo " Web   Internal"
    echo " Server  Network"
    echo " .10     .0/24"
    echo ""
    echo -e "${WHITE}DEVICE DALAM SIMULASI:${RESET}"
    echo ""
    printf "  %-20s %-18s %-20s\n" "DEVICE" "IP" "PERAN"
    echo "  ----------------------------------------------------------"
    printf "  %-20s %-18s %-20s\n" "Router" "192.168.1.1" "Default gateway"
    printf "  %-20s %-18s %-20s\n" "Web Server" "192.168.1.10" "Apache/Nginx"
    printf "  %-20s %-18s %-20s\n" "Database Server" "192.168.1.20" "MySQL"
    printf "  %-20s %-18s %-20s\n" "Admin PC" "192.168.1.50" "Workstation"
    printf "  %-20s %-18s %-20s\n" "User PC 1" "192.168.1.100" "Workstation"
    printf "  %-20s %-18s %-20s\n" "User PC 2" "192.168.1.101" "Workstation"
    echo ""
    echo -e "${WHITE}SIMULASI SERANGAN DAN MITIGASI:${RESET}"
    echo ""
    echo -e "  ${RED}Skenario 1: Port Scanning${RESET}"
    echo "  Penyerang: nmap -sV 192.168.1.0/24"
    echo "  Temuan: Port 80, 443, 3306 terbuka di web server"
    echo "  RISIKO: Database (3306) seharusnya tidak bisa diakses publik!"
    echo "  MITIGASI: Block port 3306 di firewall untuk akses eksternal"
    echo ""
    echo -e "  ${RED}Skenario 2: ARP Spoofing${RESET}"
    echo "  Penyerang di 192.168.1.150 kirim ARP palsu"
    echo "  Klaim: 'IP 192.168.1.1 (router) ada di MAC saya'"
    echo "  Efek: Semua traffic lewat komputer penyerang (MitM)"
    echo "  MITIGASI: Dynamic ARP Inspection di switch, static ARP"
    echo ""
    echo -e "  ${RED}Skenario 3: DNS Poisoning${RESET}"
    echo "  Penyerang ubah DNS cache: bank.com -> IP berbahaya"
    echo "  Korban ketik bank.com tapi diarahkan ke site palsu"
    echo "  MITIGASI: DNSSEC, DNS over HTTPS"
    pause_modul
}

lab_koneksi_lokal() {
    clear
    echo -e "${YELLOW}=== LAB: ANALISIS KONEKSI LOKAL ===${RESET}"
    echo ""
    echo "Lab ini akan menganalisis koneksi jaringan di device kamu"
    echo ""
    echo -e "${WHITE}1. Cek IP Address:${RESET}"
    if command -v ip &>/dev/null; then
        ip addr show 2>/dev/null | grep -E "(inet |inet6)" | head -10
    elif command -v ifconfig &>/dev/null; then
        ifconfig 2>/dev/null | grep -E "inet " | head -10
    else
        echo "  ip/ifconfig tidak tersedia"
    fi
    echo ""
    echo -e "${WHITE}2. Cek Default Gateway dan Routing:${RESET}"
    ip route 2>/dev/null || route -n 2>/dev/null || echo "  Tidak tersedia"
    echo ""
    echo -e "${WHITE}3. Cek Koneksi Aktif:${RESET}"
    if command -v ss &>/dev/null; then
        ss -tuln 2>/dev/null | head -20
    elif command -v netstat &>/dev/null; then
        netstat -tuln 2>/dev/null | head -20
    else
        echo "  ss/netstat tidak tersedia"
    fi
    echo ""
    echo -e "${WHITE}4. Cek ARP Table:${RESET}"
    arp -a 2>/dev/null || ip neigh 2>/dev/null | head -10 || echo "  Tidak tersedia"
    echo ""
    echo -e "${WHITE}5. DNS Resolver:${RESET}"
    cat /etc/resolv.conf 2>/dev/null || echo "  /etc/resolv.conf tidak ada"
    pause_modul
}

# Jalankan menu utama modul
menu_jaringan
