#!/bin/bash
RED='\033[0;31m'; GREEN='\033[0;32m'; YELLOW='\033[1;33m'
CYAN='\033[0;36m'; WHITE='\033[1;37m'; DIM='\033[2m'; RESET='\033[0m'

CYBERTUZ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
if [ -z "$CYBERTUZ_LANG" ]; then
    source "$CYBERTUZ_DIR/lang.sh"
    ct_load_lang || _ct_set_lang "en"
fi

pause_modul() { echo ""; echo -ne "${DIM}  $CT_ENTER${RESET}"; read -r; }

menu_jaringan() {
    while true; do
        clear
        echo -e "${RED}=== $CT_MOD_HDR_2 ===${RESET}"
        echo ""
        echo -e "  ${GREEN}[1]${RESET}  $CT_M2_1"
        echo -e "  ${GREEN}[2]${RESET}  $CT_M2_2"
        echo -e "  ${GREEN}[3]${RESET}  $CT_M2_3"
        echo -e "  ${GREEN}[4]${RESET}  $CT_M2_4"
        echo -e "  ${GREEN}[5]${RESET}  $CT_M2_5"
        echo -e "  ${GREEN}[6]${RESET}  $CT_M2_6"
        echo -e "  ${GREEN}[7]${RESET}  $CT_M2_7"
        echo -e "  ${GREEN}[8]${RESET}  $CT_M2_8"
        echo -e "  ${GREEN}[9]${RESET}  $CT_M2_9"
        echo -e "  ${RED}[0]${RESET}  $CT_BACK"
        echo ""
        echo -ne "  ${CYAN}$CT_MPROMPT${RESET}"
        read -r choice
        case $choice in
            1) belajar_osi ;;
            2) belajar_ip ;;
            3) belajar_protokol ;;
            4) belajar_dns ;;
            5) belajar_http ;;
            6) belajar_firewall ;;
            7) simulasi_packet ;;
            8) simulasi_jaringan ;;
            9) lab_koneksi_lokal ;;
            0) return ;;
            *) echo -e "${RED}$CT_INVALID${RESET}"; sleep 1 ;;
        esac
    done
}

belajar_osi() {
    clear
    echo -e "${YELLOW}=== $CT_C_M2_OSI_TITLE ===${RESET}"
    echo ""
    echo "$CT_C_M2_OSI_INTRO"
    echo ""
    echo -e "${WHITE}$CT_C_M2_OSI_LAYERS${RESET}"
    echo ""
    echo -e "  ${RED}Layer 7 - Application${RESET}"
    echo "  $CT_C_M2_L7_DESC"
    echo "  Protocol: HTTP, HTTPS, FTP, SMTP, DNS, SSH, Telnet"
    echo "  $CT_C_M2_L7_EX"
    echo ""
    echo -e "  ${RED}Layer 6 - Presentation${RESET}"
    echo "  $CT_C_M2_L6_DESC"
    echo "  Format: JPEG, PNG, MP3, SSL/TLS, ASCII, EBCDIC"
    echo "  $CT_C_M2_L6_EX"
    echo ""
    echo -e "  ${RED}Layer 5 - Session${RESET}"
    echo "  $CT_C_M2_L5_DESC"
    echo "  Protocol: NetBIOS, PPTP, SAP, L2TP"
    echo "  $CT_C_M2_L5_EX"
    echo ""
    echo -e "  ${YELLOW}Layer 4 - Transport${RESET}"
    echo "  $CT_C_M2_L4_DESC"
    echo "  Protocol: TCP (reliable), UDP (unreliable)"
    echo "  TCP: Three-way handshake (SYN, SYN-ACK, ACK)"
    echo ""
    echo -e "  ${YELLOW}Layer 3 - Network${RESET}"
    echo "  $CT_C_M2_L3_DESC"
    echo "  Protocol: IP, ICMP, OSPF, BGP, RIP"
    echo "  $CT_C_M2_L3_DEV"
    echo ""
    echo -e "  ${GREEN}Layer 2 - Data Link${RESET}"
    echo "  $CT_C_M2_L2_DESC"
    echo "  Protocol: Ethernet, Wi-Fi (802.11), ARP, PPP"
    echo "  $CT_C_M2_L2_DEV"
    echo "  $CT_C_M2_L2_ADDR"
    echo ""
    echo -e "  ${GREEN}Layer 1 - Physical${RESET}"
    echo "  $CT_C_M2_L1_DESC"
    echo "  $CT_C_M2_L1_MED"
    echo "  $CT_C_M2_L1_DEV"
    echo ""
    echo -e "${WHITE}$CT_C_M2_TCPIP_MODEL${RESET}"
    echo ""
    echo "  Application Layer  = OSI Layer 5, 6, 7"
    echo "  Transport Layer    = OSI Layer 4"
    echo "  Internet Layer     = OSI Layer 3"
    echo "  Network Access     = OSI Layer 1, 2"
    echo ""
    echo -e "${WHITE}$CT_C_M2_HANDSHAKE${RESET}"
    echo ""
    echo "  Client                     Server"
    echo "    |------- SYN ----------->|   ($CT_C_M2_HS_SYN)"
    echo "    |<------ SYN-ACK --------|   ($CT_C_M2_HS_SYNACK)"
    echo "    |------- ACK ----------->|   ($CT_C_M2_HS_ACK)"
    echo "    |====== DATA EXCHANGE ===|"
    echo "    |------- FIN ----------->|   ($CT_C_M2_HS_FIN_C)"
    echo "    |<------ ACK ------------|"
    echo "    |<------ FIN ------------|   ($CT_C_M2_HS_FIN_S)"
    echo "    |------- ACK ----------->|"
    pause_modul
}

belajar_ip() {
    clear
    echo -e "${YELLOW}=== $CT_C_M2_IP_TITLE ===${RESET}"
    echo ""
    echo -e "${WHITE}$CT_C_M2_IPV4${RESET}"
    echo "$CT_C_M2_IPV4_DESC"
    echo "$CT_C_M2_IPV4_EX"
    echo "$CT_C_M2_IPV4_RANGE"
    echo ""
    echo -e "${WHITE}$CT_C_M2_IP_CLASS${RESET}"
    echo ""
    echo "  Class A: 1.0.0.0 - 126.255.255.255 (/8)   - $CT_C_M2_CLASS_A_DESC"
    echo "  Class B: 128.0.0.0 - 191.255.255.255 (/16) - $CT_C_M2_CLASS_B_DESC"
    echo "  Class C: 192.0.0.0 - 223.255.255.255 (/24) - $CT_C_M2_CLASS_C_DESC"
    echo "  Class D: 224.0.0.0 - 239.255.255.255 (Multicast)"
    echo "  Class E: 240.0.0.0 - 255.255.255.255 (Reserved)"
    echo ""
    echo -e "${WHITE}$CT_C_M2_PRIVATE${RESET}"
    echo "  10.0.0.0/8      (Class A private)"
    echo "  172.16.0.0/12   (Class B private)"
    echo "  192.168.0.0/16  (Class C private)"
    echo "  127.0.0.0/8     (Loopback)"
    echo ""
    echo -e "${WHITE}$CT_C_M2_SUBNET${RESET}"
    echo "  /8  = 255.0.0.0       = 16,777,214 hosts"
    echo "  /16 = 255.255.0.0     = 65,534 hosts"
    echo "  /24 = 255.255.255.0   = 254 hosts"
    echo "  /25 = 255.255.255.128 = 126 hosts"
    echo "  /26 = 255.255.255.192 = 62 hosts"
    echo "  /27 = 255.255.255.224 = 30 hosts"
    echo "  /28 = 255.255.255.240 = 14 hosts"
    echo "  /29 = 255.255.255.248 = 6 hosts"
    echo "  /30 = 255.255.255.252 = 2 hosts"
    echo ""
    echo -e "${WHITE}$CT_C_M2_SUBNET_CALC${RESET}"
    echo "  192.168.1.0/24"
    echo "  $CT_C_M2_NET_ADDR : 192.168.1.0"
    echo "  $CT_C_M2_BROADCAST       : 192.168.1.255"
    echo "  $CT_C_M2_USABLE    : 192.168.1.1 - 192.168.1.254"
    echo "  $CT_C_M2_TOTAL_HOST      : 254"
    echo ""
    echo -e "${WHITE}$CT_C_M2_IPV6${RESET}"
    echo "  $CT_C_M2_IPV6_DESC"
    echo "  2001:0db8:85a3:0000:0000:8a2e:0370:7334"
    echo "  -> 2001:db8:85a3::8a2e:370:7334"
    echo ""
    echo -e "${WHITE}$CT_C_M2_SUBNET_SIM${RESET}"
    echo -ne "  $CT_C_M2_ENTER_IP"
    read -r ip_cidr
    if [[ "$ip_cidr" =~ ^([0-9]+\.[0-9]+\.[0-9]+\.[0-9]+)/([0-9]+)$ ]]; then
        local ip="${BASH_REMATCH[1]}" cidr="${BASH_REMATCH[2]}"
        local hosts=$((2 ** (32 - cidr) - 2))
        echo ""
        echo "  IP: $ip | CIDR: /$cidr | $CT_C_M2_NUM_HOSTS: $hosts"
    else
        echo "  $CT_INVALID - Format: X.X.X.X/XX"
    fi
    pause_modul
}

belajar_protokol() {
    clear
    echo -e "${YELLOW}=== $CT_C_M2_PROTO_TITLE ===${RESET}"
    echo ""
    echo -e "${WHITE}$CT_C_M2_PROTO_BY_PORT${RESET}"
    echo ""
    printf "  %-8s %-8s %-40s\n" "$CT_C_M2_PORT_HDR" "$CT_C_M2_PROTO_HDR" "$CT_C_M2_SVC_HDR"
    echo "  ----------------------------------------------------------------"
    printf "  %-8s %-8s %-40s\n" "20,21" "TCP" "$CT_C_M2_FTP_DESC"
    printf "  %-8s %-8s %-40s\n" "22"    "TCP" "$CT_C_M2_SSH_DESC"
    printf "  %-8s %-8s %-40s\n" "23"    "TCP" "$CT_C_M2_TELNET_DESC"
    printf "  %-8s %-8s %-40s\n" "25"    "TCP" "$CT_C_M2_SMTP_DESC"
    printf "  %-8s %-8s %-40s\n" "53"    "UDP/TCP" "DNS"
    printf "  %-8s %-8s %-40s\n" "67,68" "UDP" "DHCP"
    printf "  %-8s %-8s %-40s\n" "80"    "TCP" "$CT_C_M2_HTTP_DESC"
    printf "  %-8s %-8s %-40s\n" "110"   "TCP" "$CT_C_M2_POP3_DESC"
    printf "  %-8s %-8s %-40s\n" "143"   "TCP" "$CT_C_M2_IMAP_DESC"
    printf "  %-8s %-8s %-40s\n" "443"   "TCP" "$CT_C_M2_HTTPS_DESC"
    printf "  %-8s %-8s %-40s\n" "445"   "TCP" "$CT_C_M2_SMB_DESC"
    printf "  %-8s %-8s %-40s\n" "3306"  "TCP" "$CT_C_M2_MYSQL_DESC"
    printf "  %-8s %-8s %-40s\n" "3389"  "TCP" "$CT_C_M2_RDP_DESC"
    printf "  %-8s %-8s %-40s\n" "5432"  "TCP" "$CT_C_M2_PGSQL_DESC"
    printf "  %-8s %-8s %-40s\n" "6379"  "TCP" "Redis"
    printf "  %-8s %-8s %-40s\n" "27017" "TCP" "MongoDB"
    echo ""
    echo -e "${WHITE}$CT_C_M2_DANGER_PROTO${RESET}"
    echo ""
    echo -e "  ${RED}Telnet (23):${RESET} $CT_C_M2_TELNET_WARN"
    echo -e "  ${RED}FTP (21):${RESET}    $CT_C_M2_FTP_WARN"
    echo -e "  ${RED}HTTP (80):${RESET}   $CT_C_M2_HTTP_WARN"
    echo -e "  ${RED}SNMPv1/v2 (161):${RESET} $CT_C_M2_SNMP_WARN"
    pause_modul
}

belajar_dns() {
    clear
    echo -e "${YELLOW}=== $CT_C_M2_DNS_TITLE ===${RESET}"
    echo ""
    echo "$CT_C_M2_DNS_DEF"
    echo ""
    echo -e "${WHITE}$CT_C_M2_DNS_HIER${RESET}"
    echo ""
    echo "  . (Root DNS)"
    echo "  |"
    echo "  +-- .com (TLD)"
    echo "  |     |"
    echo "  |     +-- google.com (SLD)"
    echo "  |           |"
    echo "  |           +-- www.google.com"
    echo "  |           +-- mail.google.com"
    echo ""
    echo -e "${WHITE}$CT_C_M2_DNS_PROCESS${RESET}"
    echo ""
    echo "  1. $CT_C_M2_DNS_P1"
    echo "  2. $CT_C_M2_DNS_P2"
    echo "  3. $CT_C_M2_DNS_P3"
    echo "  4. $CT_C_M2_DNS_P4"
    echo "  5. $CT_C_M2_DNS_P5"
    echo "  6. $CT_C_M2_DNS_P6"
    echo "  7. $CT_C_M2_DNS_P7"
    echo "  8. $CT_C_M2_DNS_P8"
    echo ""
    echo -e "${WHITE}$CT_C_M2_DNS_RECORDS${RESET}"
    echo ""
    echo "  A     : $CT_C_M2_DNS_A"
    echo "  AAAA  : $CT_C_M2_DNS_AAAA"
    echo "  CNAME : $CT_C_M2_DNS_CNAME"
    echo "  MX    : $CT_C_M2_DNS_MX"
    echo "  NS    : $CT_C_M2_DNS_NS"
    echo "  TXT   : $CT_C_M2_DNS_TXT"
    echo "  PTR   : $CT_C_M2_DNS_PTR"
    echo "  SOA   : $CT_C_M2_DNS_SOA"
    echo ""
    echo -e "${WHITE}$CT_C_M2_DNS_SEC${RESET}"
    echo ""
    echo "  $CT_C_M2_DNS_SPOOF"
    echo "  $CT_C_M2_DNS_TUNNEL"
    echo "  $CT_C_M2_DNS_AMP"
    echo "  $CT_C_M2_DNSSEC"
    echo ""
    echo -e "${WHITE}$CT_C_M2_DNS_PRACTICE${RESET}"
    echo ""
    if command -v nslookup &>/dev/null; then
        echo "  $CT_C_M2_DNS_RUNNING"
        timeout 5 nslookup google.com 8.8.8.8 2>/dev/null || echo "  ($CT_C_M2_DNS_OFFLINE)"
    else
        echo "  $CT_C_M2_DNS_NO_TOOL"
    fi
    pause_modul
}

belajar_http() {
    clear
    echo -e "${YELLOW}=== $CT_C_M2_HTTP_TITLE ===${RESET}"
    echo ""
    echo -e "${WHITE}HTTP (HyperText Transfer Protocol)${RESET}"
    echo "$CT_C_M2_HTTP_DEF"
    echo "Port: 80 | $CT_C_M2_HTTP_NOT_ENC"
    echo ""
    echo -e "${WHITE}$CT_C_M2_HTTP_METHODS${RESET}"
    echo ""
    echo "  $CT_C_M2_GET"
    echo "  $CT_C_M2_POST"
    echo "  $CT_C_M2_PUT"
    echo "  $CT_C_M2_PATCH"
    echo "  $CT_C_M2_DELETE"
    echo "  $CT_C_M2_HEAD"
    echo "  $CT_C_M2_OPTIONS"
    echo ""
    echo -e "${WHITE}$CT_C_M2_STATUS_CODES${RESET}"
    echo ""
    echo "  $CT_C_M2_2XX"
    echo "    $CT_C_M2_200"
    echo "    $CT_C_M2_201"
    echo "    $CT_C_M2_204"
    echo ""
    echo "  $CT_C_M2_3XX"
    echo "    $CT_C_M2_301"
    echo "    $CT_C_M2_302"
    echo ""
    echo "  $CT_C_M2_4XX"
    echo "    $CT_C_M2_400"
    echo "    $CT_C_M2_401"
    echo "    $CT_C_M2_403"
    echo "    $CT_C_M2_404"
    echo ""
    echo "  $CT_C_M2_5XX"
    echo "    $CT_C_M2_500"
    echo "    $CT_C_M2_502"
    echo "    $CT_C_M2_503"
    echo ""
    echo -e "${WHITE}$CT_C_M2_HEADERS${RESET}"
    echo ""
    echo "  $CT_C_M2_REQ_HDR"
    echo "    $CT_C_M2_USERAGENT"
    echo "    $CT_C_M2_COOKIE_H"
    echo "    $CT_C_M2_AUTH_H"
    echo "    $CT_C_M2_CTYPE_H"
    echo "    $CT_C_M2_REFERER"
    echo ""
    echo "  $CT_C_M2_RESP_HDR"
    echo "    $CT_C_M2_SETCOOKIE"
    echo "    $CT_C_M2_XFO"
    echo "    $CT_C_M2_HSTS"
    echo ""
    echo -e "${WHITE}$CT_C_M2_HTTPS${RESET}"
    echo "  $CT_C_M2_HTTPS_DESC"
    echo ""
    echo "  $CT_C_M2_TLS_PROC"
    echo "    1. $CT_C_M2_TLS1"
    echo "    2. $CT_C_M2_TLS2"
    echo "    3. $CT_C_M2_TLS3"
    echo "    4. $CT_C_M2_TLS4"
    echo "    5. $CT_C_M2_TLS5"
    echo ""
    echo -e "${WHITE}$CT_C_M2_HTTP_SIM${RESET}"
    echo "  $CT_C_M2_HTTP_SIM_DESC"
    echo "  GET /index.html HTTP/1.1"
    echo "  Host: www.example.com"
    echo "  User-Agent: Mozilla/5.0"
    echo "  Accept: text/html"
    echo "  [BLANK LINE]"
    pause_modul
}

belajar_firewall() {
    clear
    echo -e "${YELLOW}=== $CT_C_M2_FW_TITLE ===${RESET}"
    echo ""
    echo "$CT_C_M2_FW_DEF2"
    echo ""
    echo -e "${WHITE}$CT_C_M2_FW_TYPES2${RESET}"
    echo ""
    echo -e "  ${CYAN}1. Packet Filter Firewall${RESET}"
    echo "  $CT_C_M2_FW1_DESC"
    echo "  $CT_C_M2_FW1_EX"
    echo ""
    echo -e "  ${CYAN}2. Stateful Inspection Firewall${RESET}"
    echo "  $CT_C_M2_FW2_DESC"
    echo ""
    echo -e "  ${CYAN}3. Application Layer Firewall (WAF)${RESET}"
    echo "  $CT_C_M2_FW3_DESC"
    echo "  $CT_C_M2_FW3_EX"
    echo ""
    echo -e "  ${CYAN}4. Next-Generation Firewall (NGFW)${RESET}"
    echo "  $CT_C_M2_FW4_DESC"
    echo "  $CT_C_M2_FW4_EX"
    echo ""
    echo -e "${WHITE}$CT_C_M2_FW_RULES${RESET}"
    echo ""
    echo "  $CT_C_M2_FW_RULES_DESC"
    echo ""
    echo "  $CT_C_M2_FW_IPRULES"
    echo "  iptables -A INPUT -p tcp --dport 22 -j ACCEPT"
    echo "  iptables -A INPUT -p tcp --dport 80 -j ACCEPT"
    echo "  iptables -A INPUT -p tcp --dport 443 -j ACCEPT"
    echo "  iptables -A INPUT -j DROP"
    echo ""
    echo -e "${WHITE}$CT_C_M2_FW_CONCEPTS${RESET}"
    echo ""
    echo "  - $CT_C_M2_FW_DEF_DENY"
    echo "  - $CT_C_M2_FW_DEF_ALLOW"
    echo "  - $CT_C_M2_FW_INGRESS"
    echo "  - $CT_C_M2_FW_EGRESS"
    echo ""
    echo "  $CT_C_M2_FW_BYPASS"
    echo "  - SSH tunneling | Protocol manipulation | Fragmentation | VPN/proxy"
    pause_modul
}

simulasi_packet() {
    clear
    echo -e "${YELLOW}=== $CT_C_M2_PKT_TITLE ===${RESET}"
    echo ""
    echo "$CT_C_M2_PKT_INTRO"
    echo ""
    echo -e "${WHITE}$CT_C_M2_ETH_STRUCT${RESET}"
    echo ""
    echo "  +------------------+------------------+------+----------+-----+"
    echo "  | Destination MAC  | Source MAC       | Type | Payload  | FCS |"
    echo "  | 6 bytes          | 6 bytes          | 2 B  | 46-1500B | 4 B |"
    echo "  +------------------+------------------+------+----------+-----+"
    echo ""
    echo -e "${WHITE}$CT_C_M2_PKT_EXAMPLE${RESET}"
    echo ""
    echo "  === PACKET #1 [TCP SYN] ==="
    echo "  $CT_C_M2_PKT_SRC    : 192.168.1.100:54231"
    echo "  $CT_C_M2_PKT_DST      : 93.184.216.34:80 | Flags: SYN"
    echo ""
    echo "  === PACKET #2 [TCP SYN-ACK] ==="
    echo "  $CT_C_M2_PKT_SRC    : 93.184.216.34:80"
    echo "  $CT_C_M2_PKT_DST      : 192.168.1.100:54231 | Flags: SYN,ACK"
    echo ""
    echo "  === PACKET #3 [HTTP GET] ==="
    echo "  Data: GET / HTTP/1.1"
    echo "        Host: example.com"
    echo "        User-Agent: Mozilla/5.0"
    echo "        Cookie: session=abc123"
    echo ""
    echo -e "${RED}$CT_C_M2_HTTP_DANGER${RESET}"
    echo ""
    echo "  $CT_C_M2_HTTP_DANGER_DESC"
    echo "  $CT_C_M2_WIRESHARK_WARN"
    echo ""
    echo -e "${GREEN}$CT_C_M2_PROTECT2${RESET}"
    echo "  - $CT_C_M2_PROTECT_1"
    echo "  - $CT_C_M2_PROTECT_2"
    echo "  - $CT_C_M2_PROTECT_3"
    pause_modul
}

simulasi_jaringan() {
    clear
    echo -e "${YELLOW}=== $CT_C_M2_NET_TOPO ===${RESET}"
    echo ""
    echo "$CT_C_M2_TOPO_INTRO"
    echo ""
    echo -e "${WHITE}$CT_C_M2_TOPO_TITLE${RESET}"
    echo ""
    echo "  Internet --> [ISP Router] --> [Firewall] --> [Switch]"
    echo "                                                  |"
    echo "                                   +------+-------+------+"
    echo "                                   |      |       |      |"
    echo "                                  DMZ  WebSrv  DBSrv  Users"
    echo "                                        .10     .20    .100+"
    echo ""
    echo -e "${WHITE}$CT_C_M2_TOPO_DEVICES${RESET}"
    echo ""
    printf "  %-20s %-18s %-20s\n" "$CT_C_M2_DEVICE" "IP" "$CT_C_M2_ROLE"
    echo "  ----------------------------------------------------------"
    printf "  %-20s %-18s %-20s\n" "Router"          "192.168.1.1"   "Default gateway"
    printf "  %-20s %-18s %-20s\n" "Web Server"      "192.168.1.10"  "Apache/Nginx"
    printf "  %-20s %-18s %-20s\n" "Database Server" "192.168.1.20"  "MySQL"
    printf "  %-20s %-18s %-20s\n" "Admin PC"        "192.168.1.50"  "Workstation"
    printf "  %-20s %-18s %-20s\n" "User PC 1"       "192.168.1.100" "Workstation"
    echo ""
    echo -e "${WHITE}$CT_C_M2_ATTACK_SIM${RESET}"
    echo ""
    echo -e "  ${RED}$CT_C_M2_SCEN1${RESET}"
    echo "  $CT_C_M2_SCEN1_FIND"
    echo "  $CT_C_M2_SCEN1_RISK"
    echo "  $CT_C_M2_SCEN1_MIT"
    echo ""
    echo -e "  ${RED}$CT_C_M2_SCEN2${RESET}"
    echo "  $CT_C_M2_SCEN2_DESC"
    echo "  $CT_C_M2_SCEN2_MIT"
    echo ""
    echo -e "  ${RED}$CT_C_M2_SCEN3${RESET}"
    echo "  $CT_C_M2_SCEN3_DESC"
    echo "  $CT_C_M2_SCEN3_MIT"
    pause_modul
}

lab_koneksi_lokal() {
    clear
    echo -e "${YELLOW}=== $CT_C_M2_LAB_TITLE ===${RESET}"
    echo ""
    echo "$CT_C_M2_LAB_INTRO"
    echo ""
    echo -e "${WHITE}$CT_C_M2_CHECK_IP${RESET}"
    if command -v ip &>/dev/null; then
        ip addr show 2>/dev/null | grep -E "(inet |inet6)" | head -5
    elif command -v ifconfig &>/dev/null; then
        ifconfig 2>/dev/null | grep "inet " | head -5
    else
        echo "  $CT_C_M2_NOT_AVAIL"
    fi
    echo ""
    echo -e "${WHITE}$CT_C_M2_CHECK_GW${RESET}"
    ip route 2>/dev/null | head -5 || route -n 2>/dev/null | head -5 || echo "  $CT_C_M2_NOT_AVAIL"
    echo ""
    echo -e "${WHITE}$CT_C_M2_CHECK_CONN${RESET}"
    if command -v ss &>/dev/null; then
        ss -tuln 2>/dev/null | head -10
    elif command -v netstat &>/dev/null; then
        netstat -tuln 2>/dev/null | head -10
    else
        echo "  $CT_C_M2_NOT_AVAIL"
    fi
    echo ""
    echo -e "${WHITE}$CT_C_M2_CHECK_ARP${RESET}"
    arp -a 2>/dev/null | head -5 || ip neigh 2>/dev/null | head -5 || echo "  $CT_C_M2_NOT_AVAIL"
    echo ""
    echo -e "${WHITE}$CT_C_M2_CHECK_DNS${RESET}"
    cat /etc/resolv.conf 2>/dev/null || echo "  $CT_C_M2_NOT_AVAIL"
    pause_modul
}

menu_jaringan
