#!/bin/bash

CYBERTUZ_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
LANG_SAVE_FILE="$CYBERTUZ_DIR/logs/lang.dat"

mkdir -p "$CYBERTUZ_DIR/logs"

_ct_set_lang() {
    local L="$1"
    CYBERTUZ_LANG="$L"

    case "$L" in

    en)
        CT_LANG_NAME="English"
        CT_SUBTITLE="Comprehensive Cyber Security Learning Platform"
        CT_FOR_EDU="For Educational Purposes and Ethical Hacking Only"
        CT_DISC_TITLE="DISCLAIMER & ETHICS STATEMENT"
        CT_DISC_1="CyberTuz is a cyber security education platform for beginners."
        CT_DISC_2="All materials are designed for legal and ethical learning only."
        CT_DISC_RULES="RULES OF USE:"
        CT_RULE_1="Use ONLY on systems you own or have explicit written permission"
        CT_RULE_2="All practice is for learning purposes only"
        CT_RULE_3="Do not use these techniques to attack other people systems"
        CT_RULE_4="Comply with all applicable laws in your country"
        CT_WARN="WARNING: Attacking systems without permission is a CRIME!"
        CT_AGREE_Q="Do you agree to the terms above? (yes/no): "
        CT_AGREE_OK="yes y"
        CT_EXIT="Thank you for using CyberTuz!"
        CT_INVALID="Invalid choice!"
        CT_ENTER="Press ENTER to continue..."
        CT_BACK="Back to Main Menu"
        CT_MENU_HDR="CYBERTUZ MAIN MENU"
        CT_M1="Basic Theory of Cyber Security"
        CT_M2="Reconnaissance & Information Gathering"
        CT_M3="Network Scanning & Enumeration"
        CT_M4="Vulnerability Assessment"
        CT_M5="Web Application Security"
        CT_M6="Cryptography & Encryption"
        CT_M7="Password Security & Cracking"
        CT_M8="Social Engineering Awareness"
        CT_M9="Network Security & Firewall"
        CT_M10="Wireless Security"
        CT_M11="Digital Forensics"
        CT_M12="Malware Analysis Basics"
        CT_M13="CTF & Practice Challenges"
        CT_M14="Tools & Complete Cheatsheet"
        CT_M15="Reports & Learning Progress"
        CT_M16="Training Arena - Leveled Practice (Newbie to Expert)"
        CT_M17="Mission System - Real Pentest Simulation Tasks"
        CT_M0="Exit"
        CT_MPROMPT="Choose menu [0-17]: "
        CT_LANG_MENU="Change Language"
        CT_CORRECT="CORRECT"
        CT_WRONG="WRONG"
        CT_HINT="HINT"
        CT_INFO="INFO"
        CT_NOTE="NOTE"
        CT_VERIFY="VERIFY"
        CT_SUCCESS="SUCCESS"
        CT_FAIL="FAIL"
        CT_SCORE="Score"
        CT_PASSED="PASSED"
        CT_NOT_PASSED="NOT PASSED - Study the material again"
        CT_ENOUGH="ENOUGH - Repeat for better results"
        CT_Q="Question"
        CT_ANS="Answer"
        CT_LVL_NB="NEWBIE"
        CT_LVL_INT="INTERMEDIATE"
        CT_LVL_ADV="ADVANCED"
        CT_LVL_EXP="EXPERT"
        CT_ARENA_HDR="CYBERTUZ - TRAINING ARENA"
        CT_MISSION_HDR="CYBERTUZ - ACTIVE MISSION"
        CT_MISSION_MENU="CYBERTUZ - MISSION SYSTEM"
        CT_MISSION_STATUS="ALL MISSIONS STATUS"
        CT_DONE="COMPLETED"
        CT_PENDING="PENDING"
        CT_LV_PROMPT="Choose level [0-8]: "
        CT_MS_PROMPT="Choose mission [0-7]: "
        CT_PROGRESS="PROGRESS"
        CT_BACKGROUND="BACKGROUND"
        CT_OBJECTIVE="MISSION OBJECTIVES"
        CT_EXEC="EXECUTION"
        CT_ANALYSIS="ANALYSIS"
        CT_RESULT="RESULT"
        CT_SAVED="Language saved."
        CT_SESSION="Session started"
        CT_EASY="EASY"
        CT_MEDIUM="MEDIUM"
        CT_HARD="HARD"
        CT_LEVEL="Level"
        CT_PRACTICE="PRACTICE"
        CT_SCENARIO="SCENARIO"
        CT_TARGET="Target"
        CT_FINDING="FINDING"
        ;;

    id)
        CT_LANG_NAME="Indonesia"
        CT_SUBTITLE="Platform Belajar Cyber Security Lengkap untuk Pemula"
        CT_FOR_EDU="Untuk Tujuan Edukasi dan Etika Hacking"
        CT_DISC_TITLE="DISCLAIMER & PERNYATAAN ETIKA"
        CT_DISC_1="CyberTuz adalah platform edukasi cyber security untuk pemula."
        CT_DISC_2="Semua materi dirancang untuk pembelajaran yang legal dan etis."
        CT_DISC_RULES="ATURAN PENGGUNAAN:"
        CT_RULE_1="Gunakan HANYA pada sistem yang kamu miliki atau sudah ada izin tertulis"
        CT_RULE_2="Semua praktik hanya untuk tujuan pembelajaran"
        CT_RULE_3="Jangan gunakan teknik ini untuk menyerang sistem orang lain"
        CT_RULE_4="Patuhi UU ITE dan semua hukum yang berlaku di negaramu"
        CT_WARN="PERINGATAN: Menyerang sistem tanpa izin adalah KEJAHATAN!"
        CT_AGREE_Q="Apakah kamu setuju dengan ketentuan di atas? (ya/tidak): "
        CT_AGREE_OK="ya y"
        CT_EXIT="Terima kasih telah menggunakan CyberTuz!"
        CT_INVALID="Pilihan tidak valid!"
        CT_ENTER="Tekan ENTER untuk lanjut..."
        CT_BACK="Kembali ke Menu Utama"
        CT_MENU_HDR="MENU UTAMA CYBERTUZ"
        CT_M1="Teori Dasar Cyber Security"
        CT_M2="Reconnaissance & Information Gathering"
        CT_M3="Network Scanning & Enumeration"
        CT_M4="Vulnerability Assessment"
        CT_M5="Web Application Security"
        CT_M6="Kriptografi & Enkripsi"
        CT_M7="Password Security & Cracking"
        CT_M8="Social Engineering Awareness"
        CT_M9="Network Security & Firewall"
        CT_M10="Wireless Security"
        CT_M11="Forensik Digital"
        CT_M12="Malware Analysis Basics"
        CT_M13="CTF & Tantangan Latihan"
        CT_M14="Tools & Cheatsheet Lengkap"
        CT_M15="Laporan & Progress Belajar"
        CT_M16="Training Arena - Latihan Berjenjang (Newbie sampai Expert)"
        CT_M17="Sistem Misi - Tugas Simulasi Pentest Nyata"
        CT_M0="Keluar"
        CT_MPROMPT="Pilih menu [0-17]: "
        CT_LANG_MENU="Ganti Bahasa"
        CT_CORRECT="BENAR"
        CT_WRONG="SALAH"
        CT_HINT="PETUNJUK"
        CT_INFO="INFO"
        CT_NOTE="CATATAN"
        CT_VERIFY="VERIFIKASI"
        CT_SUCCESS="SUKSES"
        CT_FAIL="GAGAL"
        CT_SCORE="Skor"
        CT_PASSED="LULUS"
        CT_NOT_PASSED="BELUM LULUS - Pelajari materi lagi"
        CT_ENOUGH="CUKUP - Ulangi untuk hasil lebih baik"
        CT_Q="Pertanyaan"
        CT_ANS="Jawab"
        CT_LVL_NB="PEMULA"
        CT_LVL_INT="MENENGAH"
        CT_LVL_ADV="MAHIR"
        CT_LVL_EXP="PAKAR"
        CT_ARENA_HDR="CYBERTUZ - TRAINING ARENA"
        CT_MISSION_HDR="CYBERTUZ - MISI AKTIF"
        CT_MISSION_MENU="CYBERTUZ - SISTEM MISI"
        CT_MISSION_STATUS="STATUS SEMUA MISI"
        CT_DONE="SELESAI"
        CT_PENDING="BELUM"
        CT_LV_PROMPT="Pilih level [0-8]: "
        CT_MS_PROMPT="Pilih misi [0-7]: "
        CT_PROGRESS="PROGRESS"
        CT_BACKGROUND="LATAR BELAKANG"
        CT_OBJECTIVE="OBJEKTIF MISI"
        CT_EXEC="EKSEKUSI"
        CT_ANALYSIS="ANALISIS"
        CT_RESULT="HASIL"
        CT_SAVED="Bahasa disimpan."
        CT_SESSION="Sesi dimulai"
        CT_EASY="MUDAH"
        CT_MEDIUM="SEDANG"
        CT_HARD="SULIT"
        CT_LEVEL="Level"
        CT_PRACTICE="PRAKTEK"
        CT_SCENARIO="SKENARIO"
        CT_TARGET="Target"
        CT_FINDING="TEMUAN"
        ;;

    hi)
        CT_LANG_NAME="हिन्दी"
        CT_SUBTITLE="व्यापक साइबर सुरक्षा सीखने का मंच"
        CT_FOR_EDU="शैक्षिक उद्देश्यों और नैतिक हैकिंग के लिए"
        CT_DISC_TITLE="अस्वीकरण और नैतिकता वक्तव्य"
        CT_DISC_1="CyberTuz शुरुआती लोगों के लिए साइबर सुरक्षा शिक्षा मंच है।"
        CT_DISC_2="सभी सामग्री कानूनी और नैतिक सीखने के लिए डिज़ाइन की गई है।"
        CT_DISC_RULES="उपयोग के नियम:"
        CT_RULE_1="केवल अपने सिस्टम या लिखित अनुमति वाले सिस्टम पर उपयोग करें"
        CT_RULE_2="सभी अभ्यास केवल सीखने के उद्देश्य से हैं"
        CT_RULE_3="इन तकनीकों का उपयोग दूसरों के सिस्टम पर हमले के लिए न करें"
        CT_RULE_4="अपने देश के लागू कानूनों का पालन करें"
        CT_WARN="चेतावनी: अनुमति के बिना सिस्टम पर हमला करना अपराध है!"
        CT_AGREE_Q="क्या आप उपरोक्त शर्तों से सहमत हैं? (haan/nahi): "
        CT_AGREE_OK="haan h yes y"
        CT_EXIT="CyberTuz का उपयोग करने के लिए धन्यवाद!"
        CT_INVALID="अमान्य विकल्प!"
        CT_ENTER="जारी रखने के लिए ENTER दबाएं..."
        CT_BACK="मुख्य मेनू पर वापस"
        CT_MENU_HDR="CYBERTUZ मुख्य मेनू"
        CT_M1="साइबर सुरक्षा की बुनियादी सिद्धांत"
        CT_M2="टोह और जानकारी संग्रह"
        CT_M3="नेटवर्क स्कैनिंग और गणना"
        CT_M4="भेद्यता मूल्यांकन"
        CT_M5="वेब अनुप्रयोग सुरक्षा"
        CT_M6="क्रिप्टोग्राफी और एन्क्रिप्शन"
        CT_M7="पासवर्ड सुरक्षा और क्रैकिंग"
        CT_M8="सोशल इंजीनियरिंग जागरूकता"
        CT_M9="नेटवर्क सुरक्षा और फायरवॉल"
        CT_M10="वायरलेस सुरक्षा"
        CT_M11="डिजिटल फोरेंसिक"
        CT_M12="मैलवेयर विश्लेषण बुनियादी बातें"
        CT_M13="CTF और अभ्यास चुनौतियां"
        CT_M14="टूल्स और पूर्ण चीट शीट"
        CT_M15="रिपोर्ट और सीखने की प्रगति"
        CT_M16="प्रशिक्षण क्षेत्र - स्तरीय अभ्यास"
        CT_M17="मिशन प्रणाली - वास्तविक पेनटेस्ट सिमुलेशन"
        CT_M0="बाहर निकलें"
        CT_MPROMPT="मेनू चुनें [0-17]: "
        CT_LANG_MENU="भाषा बदलें"
        CT_CORRECT="सही"
        CT_WRONG="गलत"
        CT_HINT="संकेत"
        CT_INFO="जानकारी"
        CT_NOTE="नोट"
        CT_VERIFY="सत्यापित करें"
        CT_SUCCESS="सफलता"
        CT_FAIL="विफलता"
        CT_SCORE="स्कोर"
        CT_PASSED="उत्तीर्ण"
        CT_NOT_PASSED="अनुत्तीर्ण - सामग्री फिर से पढ़ें"
        CT_ENOUGH="ठीक - बेहतर परिणाम के लिए दोहराएं"
        CT_Q="प्रश्न"
        CT_ANS="उत्तर"
        CT_LVL_NB="नौसिखिया"
        CT_LVL_INT="मध्यम"
        CT_LVL_ADV="उन्नत"
        CT_LVL_EXP="विशेषज्ञ"
        CT_ARENA_HDR="CYBERTUZ - प्रशिक्षण क्षेत्र"
        CT_MISSION_HDR="CYBERTUZ - सक्रिय मिशन"
        CT_MISSION_MENU="CYBERTUZ - मिशन प्रणाली"
        CT_MISSION_STATUS="सभी मिशन स्थिति"
        CT_DONE="पूर्ण"
        CT_PENDING="अपूर्ण"
        CT_LV_PROMPT="स्तर चुनें [0-8]: "
        CT_MS_PROMPT="मिशन चुनें [0-7]: "
        CT_PROGRESS="प्रगति"
        CT_BACKGROUND="पृष्ठभूमि"
        CT_OBJECTIVE="लक्ष्य"
        CT_EXEC="निष्पादन"
        CT_ANALYSIS="विश्लेषण"
        CT_RESULT="परिणाम"
        CT_SAVED="भाषा सहेजी गई।"
        CT_SESSION="सत्र शुरू"
        CT_EASY="आसान"
        CT_MEDIUM="मध्यम"
        CT_HARD="कठिन"
        CT_LEVEL="स्तर"
        CT_PRACTICE="अभ्यास"
        CT_SCENARIO="परिदृश्य"
        CT_TARGET="लक्ष्य"
        CT_FINDING="खोज"
        ;;

    ms)
        CT_LANG_NAME="Bahasa Melayu"
        CT_SUBTITLE="Platform Pembelajaran Keselamatan Siber Komprehensif"
        CT_FOR_EDU="Untuk Tujuan Pendidikan dan Penggodaman Beretika"
        CT_DISC_TITLE="PENAFIAN & PERNYATAAN ETIKA"
        CT_DISC_1="CyberTuz ialah platform pendidikan keselamatan siber untuk pemula."
        CT_DISC_2="Semua bahan direka untuk pembelajaran yang sah dan beretika."
        CT_DISC_RULES="PERATURAN PENGGUNAAN:"
        CT_RULE_1="Gunakan HANYA pada sistem yang anda miliki atau ada kebenaran bertulis"
        CT_RULE_2="Semua amalan adalah untuk tujuan pembelajaran sahaja"
        CT_RULE_3="Jangan gunakan teknik ini untuk menyerang sistem orang lain"
        CT_RULE_4="Patuhi semua undang-undang yang berkuat kuasa di negara anda"
        CT_WARN="AMARAN: Menyerang sistem tanpa kebenaran adalah JENAYAH!"
        CT_AGREE_Q="Adakah anda bersetuju dengan syarat di atas? (ya/tidak): "
        CT_AGREE_OK="ya y"
        CT_EXIT="Terima kasih kerana menggunakan CyberTuz!"
        CT_INVALID="Pilihan tidak sah!"
        CT_ENTER="Tekan ENTER untuk teruskan..."
        CT_BACK="Kembali ke Menu Utama"
        CT_MENU_HDR="MENU UTAMA CYBERTUZ"
        CT_M1="Teori Asas Keselamatan Siber"
        CT_M2="Peninjauan & Pengumpulan Maklumat"
        CT_M3="Pengimbasan & Penghitungan Rangkaian"
        CT_M4="Penilaian Kerentanan"
        CT_M5="Keselamatan Aplikasi Web"
        CT_M6="Kriptografi & Penyulitan"
        CT_M7="Keselamatan Kata Laluan & Pecahan"
        CT_M8="Kesedaran Kejuruteraan Sosial"
        CT_M9="Keselamatan Rangkaian & Firewall"
        CT_M10="Keselamatan Wayarles"
        CT_M11="Forensik Digital"
        CT_M12="Asas Analisis Perisian Hasad"
        CT_M13="CTF & Cabaran Latihan"
        CT_M14="Alatan & Helaian Tipu Lengkap"
        CT_M15="Laporan & Kemajuan Pembelajaran"
        CT_M16="Arena Latihan - Latihan Bertahap (Pemula ke Pakar)"
        CT_M17="Sistem Misi - Tugasan Simulasi Pentest Sebenar"
        CT_M0="Keluar"
        CT_MPROMPT="Pilih menu [0-17]: "
        CT_LANG_MENU="Tukar Bahasa"
        CT_CORRECT="BETUL"
        CT_WRONG="SALAH"
        CT_HINT="PETUNJUK"
        CT_INFO="MAKLUMAT"
        CT_NOTE="NOTA"
        CT_VERIFY="SAHKAN"
        CT_SUCCESS="BERJAYA"
        CT_FAIL="GAGAL"
        CT_SCORE="Markah"
        CT_PASSED="LULUS"
        CT_NOT_PASSED="TIDAK LULUS - Pelajari semula bahan"
        CT_ENOUGH="CUKUP - Ulang untuk keputusan lebih baik"
        CT_Q="Soalan"
        CT_ANS="Jawab"
        CT_LVL_NB="PEMULA"
        CT_LVL_INT="PERTENGAHAN"
        CT_LVL_ADV="MAHIR"
        CT_LVL_EXP="PAKAR"
        CT_ARENA_HDR="CYBERTUZ - ARENA LATIHAN"
        CT_MISSION_HDR="CYBERTUZ - MISI AKTIF"
        CT_MISSION_MENU="CYBERTUZ - SISTEM MISI"
        CT_MISSION_STATUS="STATUS SEMUA MISI"
        CT_DONE="SELESAI"
        CT_PENDING="BELUM"
        CT_LV_PROMPT="Pilih tahap [0-8]: "
        CT_MS_PROMPT="Pilih misi [0-7]: "
        CT_PROGRESS="KEMAJUAN"
        CT_BACKGROUND="LATAR BELAKANG"
        CT_OBJECTIVE="OBJEKTIF MISI"
        CT_EXEC="PELAKSANAAN"
        CT_ANALYSIS="ANALISIS"
        CT_RESULT="KEPUTUSAN"
        CT_SAVED="Bahasa disimpan."
        CT_SESSION="Sesi dimulakan"
        CT_EASY="MUDAH"
        CT_MEDIUM="SEDERHANA"
        CT_HARD="SUKAR"
        CT_LEVEL="Tahap"
        CT_PRACTICE="AMALI"
        CT_SCENARIO="SENARIO"
        CT_TARGET="Sasaran"
        CT_FINDING="PENEMUAN"
        ;;

    ru)
        CT_LANG_NAME="Русский"
        CT_SUBTITLE="Комплексная платформа обучения кибербезопасности"
        CT_FOR_EDU="Для образовательных целей и этичного хакинга"
        CT_DISC_TITLE="ОТКАЗ ОТ ОТВЕТСТВЕННОСТИ И ЗАЯВЛЕНИЕ ОБ ЭТИКЕ"
        CT_DISC_1="CyberTuz — образовательная платформа кибербезопасности для начинающих."
        CT_DISC_2="Все материалы предназначены для законного и этичного обучения."
        CT_DISC_RULES="ПРАВИЛА ИСПОЛЬЗОВАНИЯ:"
        CT_RULE_1="Используйте ТОЛЬКО на системах, которыми вы владеете или с разрешения"
        CT_RULE_2="Все практики исключительно в учебных целях"
        CT_RULE_3="Не используйте эти техники для атак на системы других людей"
        CT_RULE_4="Соблюдайте все применимые законы вашей страны"
        CT_WARN="ВНИМАНИЕ: Атака на системы без разрешения — УГОЛОВНОЕ ПРЕСТУПЛЕНИЕ!"
        CT_AGREE_Q="Вы согласны с условиями выше? (да/нет): "
        CT_AGREE_OK="да d yes y"
        CT_EXIT="Спасибо за использование CyberTuz!"
        CT_INVALID="Неверный выбор!"
        CT_ENTER="Нажмите ENTER для продолжения..."
        CT_BACK="Вернуться в главное меню"
        CT_MENU_HDR="ГЛАВНОЕ МЕНЮ CYBERTUZ"
        CT_M1="Основы теории кибербезопасности"
        CT_M2="Разведка и сбор информации"
        CT_M3="Сканирование и перечисление сети"
        CT_M4="Оценка уязвимостей"
        CT_M5="Безопасность веб-приложений"
        CT_M6="Криптография и шифрование"
        CT_M7="Безопасность паролей и взлом"
        CT_M8="Осведомлённость о социальной инженерии"
        CT_M9="Безопасность сети и брандмауэр"
        CT_M10="Беспроводная безопасность"
        CT_M11="Цифровая криминалистика"
        CT_M12="Основы анализа вредоносного ПО"
        CT_M13="CTF и практические задания"
        CT_M14="Инструменты и полная шпаргалка"
        CT_M15="Отчёты и прогресс обучения"
        CT_M16="Арена тренировок - Практика по уровням"
        CT_M17="Система миссий - Реальные задачи пентеста"
        CT_M0="Выход"
        CT_MPROMPT="Выберите меню [0-17]: "
        CT_LANG_MENU="Сменить язык"
        CT_CORRECT="ВЕРНО"
        CT_WRONG="НЕВЕРНО"
        CT_HINT="ПОДСКАЗКА"
        CT_INFO="ИНФО"
        CT_NOTE="ПРИМЕЧАНИЕ"
        CT_VERIFY="ПРОВЕРКА"
        CT_SUCCESS="УСПЕХ"
        CT_FAIL="НЕУДАЧА"
        CT_SCORE="Счёт"
        CT_PASSED="ПРОЙДЕНО"
        CT_NOT_PASSED="НЕ ПРОЙДЕНО - Изучите материал снова"
        CT_ENOUGH="ДОСТАТОЧНО - Повторите для лучшего результата"
        CT_Q="Вопрос"
        CT_ANS="Ответ"
        CT_LVL_NB="НОВИЧОК"
        CT_LVL_INT="СРЕДНИЙ"
        CT_LVL_ADV="ПРОДВИНУТЫЙ"
        CT_LVL_EXP="ЭКСПЕРТ"
        CT_ARENA_HDR="CYBERTUZ - АРЕНА ТРЕНИРОВОК"
        CT_MISSION_HDR="CYBERTUZ - АКТИВНАЯ МИССИЯ"
        CT_MISSION_MENU="CYBERTUZ - СИСТЕМА МИССИЙ"
        CT_MISSION_STATUS="СТАТУС ВСЕХ МИССИЙ"
        CT_DONE="ВЫПОЛНЕНО"
        CT_PENDING="НЕ НАЧАТО"
        CT_LV_PROMPT="Выберите уровень [0-8]: "
        CT_MS_PROMPT="Выберите миссию [0-7]: "
        CT_PROGRESS="ПРОГРЕСС"
        CT_BACKGROUND="ПРЕДЫСТОРИЯ"
        CT_OBJECTIVE="ЦЕЛИ МИССИИ"
        CT_EXEC="ВЫПОЛНЕНИЕ"
        CT_ANALYSIS="АНАЛИЗ"
        CT_RESULT="РЕЗУЛЬТАТ"
        CT_SAVED="Язык сохранён."
        CT_SESSION="Сессия начата"
        CT_EASY="ЛЁГКИЙ"
        CT_MEDIUM="СРЕДНИЙ"
        CT_HARD="СЛОЖНЫЙ"
        CT_LEVEL="Уровень"
        CT_PRACTICE="ПРАКТИКА"
        CT_SCENARIO="СЦЕНАРИЙ"
        CT_TARGET="Цель"
        CT_FINDING="НАХОДКА"
        ;;

    zh)
        CT_LANG_NAME="中文 (简体)"
        CT_SUBTITLE="全面的网络安全学习平台"
        CT_FOR_EDU="仅用于教育目的和道德黑客"
        CT_DISC_TITLE="免责声明与道德声明"
        CT_DISC_1="CyberTuz 是面向初学者的网络安全教育平台。"
        CT_DISC_2="所有材料均为合法和道德学习而设计。"
        CT_DISC_RULES="使用规则："
        CT_RULE_1="仅在您拥有或已获得书面许可的系统上使用"
        CT_RULE_2="所有实践仅用于学习目的"
        CT_RULE_3="不得将这些技术用于攻击他人系统"
        CT_RULE_4="遵守您所在国家或地区的所有适用法律"
        CT_WARN="警告：未经许可攻击系统是违法犯罪行为！"
        CT_AGREE_Q="您是否同意以上条款？(shi/bu): "
        CT_AGREE_OK="shi s yes y"
        CT_EXIT="感谢您使用 CyberTuz！"
        CT_INVALID="无效选择！"
        CT_ENTER="按 ENTER 键继续..."
        CT_BACK="返回主菜单"
        CT_MENU_HDR="CYBERTUZ 主菜单"
        CT_M1="网络安全基础理论"
        CT_M2="侦察与信息收集"
        CT_M3="网络扫描与枚举"
        CT_M4="漏洞评估"
        CT_M5="Web 应用安全"
        CT_M6="密码学与加密"
        CT_M7="密码安全与破解"
        CT_M8="社会工程学意识"
        CT_M9="网络安全与防火墙"
        CT_M10="无线安全"
        CT_M11="数字取证"
        CT_M12="恶意软件分析基础"
        CT_M13="CTF 与实践挑战"
        CT_M14="工具与完整备忘单"
        CT_M15="报告与学习进度"
        CT_M16="训练竞技场 - 分级练习"
        CT_M17="任务系统 - 真实渗透测试模拟任务"
        CT_M0="退出"
        CT_MPROMPT="选择菜单 [0-17]: "
        CT_LANG_MENU="切换语言"
        CT_CORRECT="正确"
        CT_WRONG="错误"
        CT_HINT="提示"
        CT_INFO="信息"
        CT_NOTE="注意"
        CT_VERIFY="验证"
        CT_SUCCESS="成功"
        CT_FAIL="失败"
        CT_SCORE="得分"
        CT_PASSED="通过"
        CT_NOT_PASSED="未通过 - 请重新学习材料"
        CT_ENOUGH="尚可 - 重复练习以获得更好结果"
        CT_Q="问题"
        CT_ANS="回答"
        CT_LVL_NB="新手"
        CT_LVL_INT="中级"
        CT_LVL_ADV="高级"
        CT_LVL_EXP="专家"
        CT_ARENA_HDR="CYBERTUZ - 训练竞技场"
        CT_MISSION_HDR="CYBERTUZ - 活跃任务"
        CT_MISSION_MENU="CYBERTUZ - 任务系统"
        CT_MISSION_STATUS="所有任务状态"
        CT_DONE="已完成"
        CT_PENDING="未完成"
        CT_LV_PROMPT="选择级别 [0-8]: "
        CT_MS_PROMPT="选择任务 [0-7]: "
        CT_PROGRESS="进度"
        CT_BACKGROUND="背景"
        CT_OBJECTIVE="任务目标"
        CT_EXEC="执行"
        CT_ANALYSIS="分析"
        CT_RESULT="结果"
        CT_SAVED="语言已保存。"
        CT_SESSION="会话开始"
        CT_EASY="简单"
        CT_MEDIUM="中等"
        CT_HARD="困难"
        CT_LEVEL="级别"
        CT_PRACTICE="实践"
        CT_SCENARIO="场景"
        CT_TARGET="目标"
        CT_FINDING="发现"
        ;;

    ja)
        CT_LANG_NAME="日本語"
        CT_SUBTITLE="包括的なサイバーセキュリティ学習プラットフォーム"
        CT_FOR_EDU="教育目的と倫理的ハッキングのためのみ"
        CT_DISC_TITLE="免責事項と倫理声明"
        CT_DISC_1="CyberTuz は初心者向けサイバーセキュリティ教育プラットフォームです。"
        CT_DISC_2="すべての教材は合法的かつ倫理的な学習のために設計されています。"
        CT_DISC_RULES="利用規則："
        CT_RULE_1="自分が所有するシステムまたは書面による許可を得たシステムのみで使用"
        CT_RULE_2="すべての実践は学習目的のみ"
        CT_RULE_3="これらの技術を他人のシステムへの攻撃に使用しないこと"
        CT_RULE_4="お住まいの国のすべての適用法に従うこと"
        CT_WARN="警告：許可なくシステムを攻撃することは犯罪です！"
        CT_AGREE_Q="上記の条件に同意しますか？(hai/iie): "
        CT_AGREE_OK="hai h yes y"
        CT_EXIT="CyberTuz をご利用いただきありがとうございます！"
        CT_INVALID="無効な選択です！"
        CT_ENTER="続けるには ENTER を押してください..."
        CT_BACK="メインメニューに戻る"
        CT_MENU_HDR="CYBERTUZ メインメニュー"
        CT_M1="サイバーセキュリティの基礎理論"
        CT_M2="偵察と情報収集"
        CT_M3="ネットワークスキャンと列挙"
        CT_M4="脆弱性評価"
        CT_M5="Webアプリケーションセキュリティ"
        CT_M6="暗号学と暗号化"
        CT_M7="パスワードセキュリティとクラッキング"
        CT_M8="ソーシャルエンジニアリング意識"
        CT_M9="ネットワークセキュリティとファイアウォール"
        CT_M10="ワイヤレスセキュリティ"
        CT_M11="デジタルフォレンジック"
        CT_M12="マルウェア解析の基礎"
        CT_M13="CTFと練習チャレンジ"
        CT_M14="ツールと完全なチートシート"
        CT_M15="レポートと学習進捗"
        CT_M16="トレーニングアリーナ - レベル別練習"
        CT_M17="ミッションシステム - 実際のペンテストシミュレーション"
        CT_M0="終了"
        CT_MPROMPT="メニューを選択 [0-17]: "
        CT_LANG_MENU="言語を変更"
        CT_CORRECT="正解"
        CT_WRONG="不正解"
        CT_HINT="ヒント"
        CT_INFO="情報"
        CT_NOTE="注意"
        CT_VERIFY="確認"
        CT_SUCCESS="成功"
        CT_FAIL="失敗"
        CT_SCORE="スコア"
        CT_PASSED="合格"
        CT_NOT_PASSED="不合格 - もう一度教材を学習してください"
        CT_ENOUGH="十分 - より良い結果のために繰り返してください"
        CT_Q="質問"
        CT_ANS="回答"
        CT_LVL_NB="初心者"
        CT_LVL_INT="中級"
        CT_LVL_ADV="上級"
        CT_LVL_EXP="エキスパート"
        CT_ARENA_HDR="CYBERTUZ - トレーニングアリーナ"
        CT_MISSION_HDR="CYBERTUZ - アクティブミッション"
        CT_MISSION_MENU="CYBERTUZ - ミッションシステム"
        CT_MISSION_STATUS="全ミッションステータス"
        CT_DONE="完了"
        CT_PENDING="未完了"
        CT_LV_PROMPT="レベルを選択 [0-8]: "
        CT_MS_PROMPT="ミッションを選択 [0-7]: "
        CT_PROGRESS="進捗"
        CT_BACKGROUND="背景"
        CT_OBJECTIVE="ミッション目標"
        CT_EXEC="実行"
        CT_ANALYSIS="分析"
        CT_RESULT="結果"
        CT_SAVED="言語が保存されました。"
        CT_SESSION="セッション開始"
        CT_EASY="簡単"
        CT_MEDIUM="中級"
        CT_HARD="難しい"
        CT_LEVEL="レベル"
        CT_PRACTICE="実践"
        CT_SCENARIO="シナリオ"
        CT_TARGET="ターゲット"
        CT_FINDING="発見"
        ;;

    th)
        CT_LANG_NAME="ภาษาไทย"
        CT_SUBTITLE="แพลตฟอร์มการเรียนรู้ความปลอดภัยไซเบอร์แบบครบวงจร"
        CT_FOR_EDU="สำหรับวัตถุประสงค์ทางการศึกษาและการแฮ็กอย่างมีจริยธรรมเท่านั้น"
        CT_DISC_TITLE="ข้อสงวนสิทธิ์และคำแถลงด้านจริยธรรม"
        CT_DISC_1="CyberTuz คือแพลตฟอร์มการศึกษาความปลอดภัยไซเบอร์สำหรับผู้เริ่มต้น"
        CT_DISC_2="เนื้อหาทั้งหมดออกแบบมาเพื่อการเรียนรู้ที่ถูกกฎหมายและมีจริยธรรม"
        CT_DISC_RULES="กฎการใช้งาน:"
        CT_RULE_1="ใช้บนระบบที่คุณเป็นเจ้าของหรือได้รับอนุญาตเป็นลายลักษณ์อักษรเท่านั้น"
        CT_RULE_2="การฝึกทั้งหมดเพื่อวัตถุประสงค์การเรียนรู้เท่านั้น"
        CT_RULE_3="ห้ามใช้เทคนิคเหล่านี้โจมตีระบบของผู้อื่น"
        CT_RULE_4="ปฏิบัติตามกฎหมายที่บังคับใช้ในประเทศของคุณ"
        CT_WARN="คำเตือน: การโจมตีระบบโดยไม่ได้รับอนุญาตเป็นอาชญากรรม!"
        CT_AGREE_Q="คุณเห็นด้วยกับเงื่อนไขข้างต้นหรือไม่? (chai/mai): "
        CT_AGREE_OK="chai c yes y"
        CT_EXIT="ขอบคุณที่ใช้ CyberTuz!"
        CT_INVALID="ตัวเลือกไม่ถูกต้อง!"
        CT_ENTER="กด ENTER เพื่อดำเนินการต่อ..."
        CT_BACK="กลับไปที่เมนูหลัก"
        CT_MENU_HDR="เมนูหลัก CYBERTUZ"
        CT_M1="ทฤษฎีพื้นฐานความปลอดภัยไซเบอร์"
        CT_M2="การลาดตระเวนและการรวบรวมข้อมูล"
        CT_M3="การสแกนและการระบุเครือข่าย"
        CT_M4="การประเมินช่องโหว่"
        CT_M5="ความปลอดภัยของเว็บแอปพลิเคชัน"
        CT_M6="การเข้ารหัสและการเข้ารหัสลับ"
        CT_M7="ความปลอดภัยรหัสผ่านและการแคร็ก"
        CT_M8="การตระหนักถึงวิศวกรรมสังคม"
        CT_M9="ความปลอดภัยเครือข่ายและไฟร์วอลล์"
        CT_M10="ความปลอดภัยไร้สาย"
        CT_M11="นิติวิทยาศาสตร์ดิจิทัล"
        CT_M12="พื้นฐานการวิเคราะห์มัลแวร์"
        CT_M13="CTF และความท้าทายในการฝึกฝน"
        CT_M14="เครื่องมือและชีทสรุปฉบับสมบูรณ์"
        CT_M15="รายงานและความคืบหน้าการเรียนรู้"
        CT_M16="สนามฝึก - การฝึกระดับต่างๆ"
        CT_M17="ระบบภารกิจ - การจำลองเพนเทสต์จริง"
        CT_M0="ออก"
        CT_MPROMPT="เลือกเมนู [0-17]: "
        CT_LANG_MENU="เปลี่ยนภาษา"
        CT_CORRECT="ถูกต้อง"
        CT_WRONG="ผิด"
        CT_HINT="คำใบ้"
        CT_INFO="ข้อมูล"
        CT_NOTE="หมายเหตุ"
        CT_VERIFY="ยืนยัน"
        CT_SUCCESS="สำเร็จ"
        CT_FAIL="ล้มเหลว"
        CT_SCORE="คะแนน"
        CT_PASSED="ผ่าน"
        CT_NOT_PASSED="ไม่ผ่าน - ศึกษาเนื้อหาอีกครั้ง"
        CT_ENOUGH="พอใช้ - ทำซ้ำเพื่อผลลัพธ์ที่ดีขึ้น"
        CT_Q="คำถาม"
        CT_ANS="คำตอบ"
        CT_LVL_NB="มือใหม่"
        CT_LVL_INT="ระดับกลาง"
        CT_LVL_ADV="ขั้นสูง"
        CT_LVL_EXP="ผู้เชี่ยวชาญ"
        CT_ARENA_HDR="CYBERTUZ - สนามฝึก"
        CT_MISSION_HDR="CYBERTUZ - ภารกิจที่ใช้งาน"
        CT_MISSION_MENU="CYBERTUZ - ระบบภารกิจ"
        CT_MISSION_STATUS="สถานะภารกิจทั้งหมด"
        CT_DONE="เสร็จสิ้น"
        CT_PENDING="ยังไม่เสร็จ"
        CT_LV_PROMPT="เลือกระดับ [0-8]: "
        CT_MS_PROMPT="เลือกภารกิจ [0-7]: "
        CT_PROGRESS="ความคืบหน้า"
        CT_BACKGROUND="ภูมิหลัง"
        CT_OBJECTIVE="วัตถุประสงค์ภารกิจ"
        CT_EXEC="การดำเนินการ"
        CT_ANALYSIS="การวิเคราะห์"
        CT_RESULT="ผลลัพธ์"
        CT_SAVED="บันทึกภาษาแล้ว"
        CT_SESSION="เริ่มเซสชัน"
        CT_EASY="ง่าย"
        CT_MEDIUM="ปานกลาง"
        CT_HARD="ยาก"
        CT_LEVEL="ระดับ"
        CT_PRACTICE="ฝึกปฏิบัติ"
        CT_SCENARIO="สถานการณ์"
        CT_TARGET="เป้าหมาย"
        CT_FINDING="สิ่งที่ค้นพบ"
        ;;

    vi)
        CT_LANG_NAME="Tieng Viet"
        CT_SUBTITLE="Nen tang hoc bao mat mang toan dien"
        CT_FOR_EDU="Danh cho muc dich giao duc va hack dao duc"
        CT_DISC_TITLE="TUYEN BO MIEN TRU TRACH NHIEM VA DAO DUC"
        CT_DISC_1="CyberTuz la nen tang giao duc an ninh mang danh cho nguoi moi bat dau."
        CT_DISC_2="Tat ca tai lieu duoc thiet ke cho viec hoc hop phap va co dao duc."
        CT_DISC_RULES="QUY TAC SU DUNG:"
        CT_RULE_1="Chi su dung tren he thong ban so huu hoac co su cho phep bang van ban"
        CT_RULE_2="Tat ca thuc hanh chi danh cho muc dich hoc tap"
        CT_RULE_3="Khong su dung ky thuat nay de tan cong he thong nguoi khac"
        CT_RULE_4="Tuan thu luat phap ap dung tai quoc gia cua ban"
        CT_WARN="CANH BAO: Tan cong he thong ma khong co su cho phep la TOI PHAM!"
        CT_AGREE_Q="Ban co dong y voi cac dieu khoan tren khong? (co/khong): "
        CT_AGREE_OK="co c yes y"
        CT_EXIT="Cam on ban da su dung CyberTuz!"
        CT_INVALID="Lua chon khong hop le!"
        CT_ENTER="Nhan ENTER de tiep tuc..."
        CT_BACK="Quay lai menu chinh"
        CT_MENU_HDR="MENU CHINH CYBERTUZ"
        CT_M1="Ly thuyet co ban ve bao mat mang"
        CT_M2="Trinh sat va thu thap thong tin"
        CT_M3="Quet va liet ke mang"
        CT_M4="Danh gia lo hong"
        CT_M5="Bao mat ung dung Web"
        CT_M6="Mat ma hoc va ma hoa"
        CT_M7="Bao mat mat khau va be khoa"
        CT_M8="Nhan thuc ve ky thuat xa hoi"
        CT_M9="Bao mat mang va tuong lua"
        CT_M10="Bao mat khong day"
        CT_M11="Dieu tra so"
        CT_M12="Co ban phan tich phan mem doc hai"
        CT_M13="CTF va thach thuc thuc hanh"
        CT_M14="Cong cu va bang gian lan day du"
        CT_M15="Bao cao va tien do hoc tap"
        CT_M16="Dau truong huan luyen - Thuc hanh theo cap do"
        CT_M17="He thong nhiem vu - Mo phong pentest thuc te"
        CT_M0="Thoat"
        CT_MPROMPT="Chon menu [0-17]: "
        CT_LANG_MENU="Doi ngon ngu"
        CT_CORRECT="DUNG"
        CT_WRONG="SAI"
        CT_HINT="GOI Y"
        CT_INFO="THONG TIN"
        CT_NOTE="LUU Y"
        CT_VERIFY="XAC NHAN"
        CT_SUCCESS="THANH CONG"
        CT_FAIL="THAT BAI"
        CT_SCORE="Diem"
        CT_PASSED="DAT"
        CT_NOT_PASSED="CHUA DAT - Hoc lai tai lieu"
        CT_ENOUGH="DU - Lap lai de co ket qua tot hon"
        CT_Q="Cau hoi"
        CT_ANS="Tra loi"
        CT_LVL_NB="NGUOI MOI"
        CT_LVL_INT="TRUNG CAP"
        CT_LVL_ADV="NANG CAO"
        CT_LVL_EXP="CHUYEN GIA"
        CT_ARENA_HDR="CYBERTUZ - DAU TRUONG HUAN LUYEN"
        CT_MISSION_HDR="CYBERTUZ - NHIEM VU DANG HOAT DONG"
        CT_MISSION_MENU="CYBERTUZ - HE THONG NHIEM VU"
        CT_MISSION_STATUS="TRANG THAI TAT CA NHIEM VU"
        CT_DONE="HOAN THANH"
        CT_PENDING="CHUA XONG"
        CT_LV_PROMPT="Chon cap do [0-8]: "
        CT_MS_PROMPT="Chon nhiem vu [0-7]: "
        CT_PROGRESS="TIEN DO"
        CT_BACKGROUND="BOI CANH"
        CT_OBJECTIVE="MUC TIEU NHIEM VU"
        CT_EXEC="THUC THI"
        CT_ANALYSIS="PHAN TICH"
        CT_RESULT="KET QUA"
        CT_SAVED="Da luu ngon ngu."
        CT_SESSION="Phien bat dau"
        CT_EASY="DE"
        CT_MEDIUM="TRUNG BINH"
        CT_HARD="KHO"
        CT_LEVEL="Cap do"
        CT_PRACTICE="THUC HANH"
        CT_SCENARIO="TINH HUONG"
        CT_TARGET="Muc tieu"
        CT_FINDING="PHAT HIEN"
        ;;

    ar)
        CT_LANG_NAME="العربية"
        CT_SUBTITLE="منصة تعلم الأمن السيبراني الشاملة"
        CT_FOR_EDU="لأغراض تعليمية والقرصنة الأخلاقية فقط"
        CT_DISC_TITLE="إخلاء المسؤولية وبيان الأخلاقيات"
        CT_DISC_1=".CyberTuz منصة تعليم الأمن السيبراني للمبتدئين"
        CT_DISC_2=".جميع المواد مصممة للتعلم القانوني والأخلاقي فقط"
        CT_DISC_RULES=":قواعد الاستخدام"
        CT_RULE_1="استخدم فقط على الأنظمة التي تمتلكها أو لديك إذن خطي صريح"
        CT_RULE_2="جميع الممارسات لأغراض التعلم فقط"
        CT_RULE_3="لا تستخدم هذه التقنيات لمهاجمة أنظمة الآخرين"
        CT_RULE_4="الالتزام بجميع القوانين المعمول بها في بلدك"
        CT_WARN="!تحذير: مهاجمة الأنظمة بدون إذن جريمة جنائية"
        CT_AGREE_Q="هل توافق على الشروط أعلاه؟ (naam/la): "
        CT_AGREE_OK="naam n yes y"
        CT_EXIT="!شكرًا لاستخدام CyberTuz"
        CT_INVALID="!اختيار غير صالح"
        CT_ENTER="...اضغط ENTER للمتابعة"
        CT_BACK="العودة إلى القائمة الرئيسية"
        CT_MENU_HDR="القائمة الرئيسية لـ CYBERTUZ"
        CT_M1="النظرية الأساسية للأمن السيبراني"
        CT_M2="الاستطلاع وجمع المعلومات"
        CT_M3="فحص الشبكة والتعداد"
        CT_M4="تقييم الثغرات الأمنية"
        CT_M5="أمان تطبيقات الويب"
        CT_M6="التشفير والتعمية"
        CT_M7="أمان كلمات المرور وتكسيرها"
        CT_M8="التوعية بالهندسة الاجتماعية"
        CT_M9="أمان الشبكة وجدار الحماية"
        CT_M10="الأمان اللاسلكي"
        CT_M11="الطب الشرعي الرقمي"
        CT_M12="أساسيات تحليل البرامج الضارة"
        CT_M13="CTF وتحديات الممارسة"
        CT_M14="الأدوات وورقة الغش الكاملة"
        CT_M15="التقارير وتقدم التعلم"
        CT_M16="حلبة التدريب - ممارسة متدرجة المستويات"
        CT_M17="نظام المهام - محاكاة اختبار اختراق حقيقي"
        CT_M0="خروج"
        CT_MPROMPT="اختر القائمة [0-17]: "
        CT_LANG_MENU="تغيير اللغة"
        CT_CORRECT="صحيح"
        CT_WRONG="خطأ"
        CT_HINT="تلميح"
        CT_INFO="معلومة"
        CT_NOTE="ملاحظة"
        CT_VERIFY="تحقق"
        CT_SUCCESS="نجاح"
        CT_FAIL="فشل"
        CT_SCORE="النقاط"
        CT_PASSED="ناجح"
        CT_NOT_PASSED="لم تنجح - أعد دراسة المادة"
        CT_ENOUGH="مقبول - كرر للحصول على نتائج أفضل"
        CT_Q="سؤال"
        CT_ANS="إجابة"
        CT_LVL_NB="مبتدئ"
        CT_LVL_INT="متوسط"
        CT_LVL_ADV="متقدم"
        CT_LVL_EXP="خبير"
        CT_ARENA_HDR="CYBERTUZ - حلبة التدريب"
        CT_MISSION_HDR="CYBERTUZ - المهمة النشطة"
        CT_MISSION_MENU="CYBERTUZ - نظام المهام"
        CT_MISSION_STATUS="حالة جميع المهام"
        CT_DONE="مكتمل"
        CT_PENDING="غير مكتمل"
        CT_LV_PROMPT="اختر المستوى [0-8]: "
        CT_MS_PROMPT="اختر المهمة [0-7]: "
        CT_PROGRESS="التقدم"
        CT_BACKGROUND="الخلفية"
        CT_OBJECTIVE="أهداف المهمة"
        CT_EXEC="التنفيذ"
        CT_ANALYSIS="التحليل"
        CT_RESULT="النتيجة"
        CT_SAVED="تم حفظ اللغة."
        CT_SESSION="بدأت الجلسة"
        CT_EASY="سهل"
        CT_MEDIUM="متوسط"
        CT_HARD="صعب"
        CT_LEVEL="المستوى"
        CT_PRACTICE="تطبيق"
        CT_SCENARIO="سيناريو"
        CT_TARGET="الهدف"
        CT_FINDING="نتيجة البحث"
        ;;

    es)
        CT_LANG_NAME="Español"
        CT_SUBTITLE="Plataforma integral de aprendizaje de ciberseguridad"
        CT_FOR_EDU="Solo para propositos educativos y hacking etico"
        CT_DISC_TITLE="DESCARGO DE RESPONSABILIDAD Y DECLARACION ETICA"
        CT_DISC_1="CyberTuz es una plataforma de educacion en ciberseguridad para principiantes."
        CT_DISC_2="Todos los materiales estan disenados para el aprendizaje legal y etico."
        CT_DISC_RULES="REGLAS DE USO:"
        CT_RULE_1="Usar SOLO en sistemas que posee o tiene permiso escrito explicito"
        CT_RULE_2="Todas las practicas son solo para propositos de aprendizaje"
        CT_RULE_3="No use estas tecnicas para atacar sistemas de otras personas"
        CT_RULE_4="Cumplir con todas las leyes aplicables en su pais"
        CT_WARN="ADVERTENCIA: Atacar sistemas sin permiso es un DELITO CRIMINAL!"
        CT_AGREE_Q="Esta de acuerdo con los terminos anteriores? (si/no): "
        CT_AGREE_OK="si s yes y"
        CT_EXIT="Gracias por usar CyberTuz!"
        CT_INVALID="Opcion invalida!"
        CT_ENTER="Presione ENTER para continuar..."
        CT_BACK="Volver al menu principal"
        CT_MENU_HDR="MENU PRINCIPAL DE CYBERTUZ"
        CT_M1="Teoria basica de ciberseguridad"
        CT_M2="Reconocimiento y recopilacion de informacion"
        CT_M3="Escaneo de red y enumeracion"
        CT_M4="Evaluacion de vulnerabilidades"
        CT_M5="Seguridad de aplicaciones web"
        CT_M6="Criptografia y cifrado"
        CT_M7="Seguridad de contrasenas y crackeo"
        CT_M8="Conciencia de ingenieria social"
        CT_M9="Seguridad de red y firewall"
        CT_M10="Seguridad inalambrica"
        CT_M11="Forense digital"
        CT_M12="Conceptos basicos de analisis de malware"
        CT_M13="CTF y desafios de practica"
        CT_M14="Herramientas y hoja de trucos completa"
        CT_M15="Informes y progreso de aprendizaje"
        CT_M16="Arena de entrenamiento - Practica por niveles"
        CT_M17="Sistema de misiones - Tareas de simulacion de pentest real"
        CT_M0="Salir"
        CT_MPROMPT="Elegir menu [0-17]: "
        CT_LANG_MENU="Cambiar idioma"
        CT_CORRECT="CORRECTO"
        CT_WRONG="INCORRECTO"
        CT_HINT="PISTA"
        CT_INFO="INFO"
        CT_NOTE="NOTA"
        CT_VERIFY="VERIFICAR"
        CT_SUCCESS="EXITO"
        CT_FAIL="FALLO"
        CT_SCORE="Puntuacion"
        CT_PASSED="APROBADO"
        CT_NOT_PASSED="NO APROBADO - Estudie el material nuevamente"
        CT_ENOUGH="SUFICIENTE - Repita para mejores resultados"
        CT_Q="Pregunta"
        CT_ANS="Respuesta"
        CT_LVL_NB="PRINCIPIANTE"
        CT_LVL_INT="INTERMEDIO"
        CT_LVL_ADV="AVANZADO"
        CT_LVL_EXP="EXPERTO"
        CT_ARENA_HDR="CYBERTUZ - ARENA DE ENTRENAMIENTO"
        CT_MISSION_HDR="CYBERTUZ - MISION ACTIVA"
        CT_MISSION_MENU="CYBERTUZ - SISTEMA DE MISIONES"
        CT_MISSION_STATUS="ESTADO DE TODAS LAS MISIONES"
        CT_DONE="COMPLETADO"
        CT_PENDING="PENDIENTE"
        CT_LV_PROMPT="Elegir nivel [0-8]: "
        CT_MS_PROMPT="Elegir mision [0-7]: "
        CT_PROGRESS="PROGRESO"
        CT_BACKGROUND="ANTECEDENTES"
        CT_OBJECTIVE="OBJETIVOS DE LA MISION"
        CT_EXEC="EJECUCION"
        CT_ANALYSIS="ANALISIS"
        CT_RESULT="RESULTADO"
        CT_SAVED="Idioma guardado."
        CT_SESSION="Sesion iniciada"
        CT_EASY="FACIL"
        CT_MEDIUM="MEDIO"
        CT_HARD="DIFICIL"
        CT_LEVEL="Nivel"
        CT_PRACTICE="PRACTICA"
        CT_SCENARIO="ESCENARIO"
        CT_TARGET="Objetivo"
        CT_FINDING="HALLAZGO"
        ;;

    it)
        CT_LANG_NAME="Italiano"
        CT_SUBTITLE="Piattaforma completa per l'apprendimento della sicurezza informatica"
        CT_FOR_EDU="Solo per scopi educativi e hacking etico"
        CT_DISC_TITLE="DICHIARAZIONE DI NON RESPONSABILITA ED ETICA"
        CT_DISC_1="CyberTuz e una piattaforma educativa sulla sicurezza informatica per principianti."
        CT_DISC_2="Tutti i materiali sono progettati per l'apprendimento legale ed etico."
        CT_DISC_RULES="REGOLE DI UTILIZZO:"
        CT_RULE_1="Usa SOLO su sistemi di tua proprieta o con esplicito permesso scritto"
        CT_RULE_2="Tutte le pratiche sono solo per scopi di apprendimento"
        CT_RULE_3="Non usare queste tecniche per attaccare i sistemi altrui"
        CT_RULE_4="Rispetta tutte le leggi applicabili nel tuo paese"
        CT_WARN="ATTENZIONE: Attaccare sistemi senza permesso e un REATO PENALE!"
        CT_AGREE_Q="Sei d'accordo con i termini sopra? (si/no): "
        CT_AGREE_OK="si s yes y"
        CT_EXIT="Grazie per aver usato CyberTuz!"
        CT_INVALID="Scelta non valida!"
        CT_ENTER="Premi ENTER per continuare..."
        CT_BACK="Torna al menu principale"
        CT_MENU_HDR="MENU PRINCIPALE CYBERTUZ"
        CT_M1="Teoria di base della sicurezza informatica"
        CT_M2="Ricognizione e raccolta di informazioni"
        CT_M3="Scansione di rete ed enumerazione"
        CT_M4="Valutazione delle vulnerabilita"
        CT_M5="Sicurezza delle applicazioni Web"
        CT_M6="Crittografia e cifratura"
        CT_M7="Sicurezza delle password e cracking"
        CT_M8="Consapevolezza dell'ingegneria sociale"
        CT_M9="Sicurezza di rete e firewall"
        CT_M10="Sicurezza wireless"
        CT_M11="Informatica forense"
        CT_M12="Nozioni di base sull'analisi del malware"
        CT_M13="CTF e sfide pratiche"
        CT_M14="Strumenti e cheatsheet completo"
        CT_M15="Report e progressi di apprendimento"
        CT_M16="Arena di allenamento - Pratica a livelli"
        CT_M17="Sistema missioni - Simulazione pentest reale"
        CT_M0="Esci"
        CT_MPROMPT="Scegli menu [0-17]: "
        CT_LANG_MENU="Cambia lingua"
        CT_CORRECT="CORRETTO"
        CT_WRONG="ERRATO"
        CT_HINT="SUGGERIMENTO"
        CT_INFO="INFO"
        CT_NOTE="NOTA"
        CT_VERIFY="VERIFICA"
        CT_SUCCESS="SUCCESSO"
        CT_FAIL="FALLIMENTO"
        CT_SCORE="Punteggio"
        CT_PASSED="SUPERATO"
        CT_NOT_PASSED="NON SUPERATO - Studia di nuovo il materiale"
        CT_ENOUGH="SUFFICIENTE - Ripeti per risultati migliori"
        CT_Q="Domanda"
        CT_ANS="Risposta"
        CT_LVL_NB="PRINCIPIANTE"
        CT_LVL_INT="INTERMEDIO"
        CT_LVL_ADV="AVANZATO"
        CT_LVL_EXP="ESPERTO"
        CT_ARENA_HDR="CYBERTUZ - ARENA DI ALLENAMENTO"
        CT_MISSION_HDR="CYBERTUZ - MISSIONE ATTIVA"
        CT_MISSION_MENU="CYBERTUZ - SISTEMA MISSIONI"
        CT_MISSION_STATUS="STATO DI TUTTE LE MISSIONI"
        CT_DONE="COMPLETATO"
        CT_PENDING="IN SOSPESO"
        CT_LV_PROMPT="Scegli livello [0-8]: "
        CT_MS_PROMPT="Scegli missione [0-7]: "
        CT_PROGRESS="PROGRESSO"
        CT_BACKGROUND="BACKGROUND"
        CT_OBJECTIVE="OBIETTIVI DELLA MISSIONE"
        CT_EXEC="ESECUZIONE"
        CT_ANALYSIS="ANALISI"
        CT_RESULT="RISULTATO"
        CT_SAVED="Lingua salvata."
        CT_SESSION="Sessione iniziata"
        CT_EASY="FACILE"
        CT_MEDIUM="MEDIO"
        CT_HARD="DIFFICILE"
        CT_LEVEL="Livello"
        CT_PRACTICE="PRATICA"
        CT_SCENARIO="SCENARIO"
        CT_TARGET="Obiettivo"
        CT_FINDING="RISULTATO"
        ;;

    ko)
        CT_LANG_NAME="한국어"
        CT_SUBTITLE="종합 사이버 보안 학습 플랫폼"
        CT_FOR_EDU="교육 목적 및 윤리적 해킹을 위한 것입니다"
        CT_DISC_TITLE="면책 조항 및 윤리 성명"
        CT_DISC_1="CyberTuz는 초보자를 위한 사이버 보안 교육 플랫폼입니다."
        CT_DISC_2="모든 자료는 합법적이고 윤리적인 학습을 위해 설계되었습니다."
        CT_DISC_RULES="사용 규칙:"
        CT_RULE_1="본인 소유 시스템 또는 서면 허가를 받은 시스템에서만 사용"
        CT_RULE_2="모든 실습은 학습 목적으로만 사용"
        CT_RULE_3="이 기술을 타인의 시스템 공격에 사용하지 마십시오"
        CT_RULE_4="귀국의 모든 적용 법률을 준수하십시오"
        CT_WARN="경고: 허가 없이 시스템을 공격하는 것은 형사 범죄입니다!"
        CT_AGREE_Q="위 조건에 동의하십니까? (ye/anio): "
        CT_AGREE_OK="ye y yes"
        CT_EXIT="CyberTuz를 이용해 주셔서 감사합니다!"
        CT_INVALID="잘못된 선택입니다!"
        CT_ENTER="계속하려면 ENTER를 누르세요..."
        CT_BACK="메인 메뉴로 돌아가기"
        CT_MENU_HDR="CYBERTUZ 메인 메뉴"
        CT_M1="사이버 보안 기초 이론"
        CT_M2="정찰 및 정보 수집"
        CT_M3="네트워크 스캐닝 및 열거"
        CT_M4="취약점 평가"
        CT_M5="웹 애플리케이션 보안"
        CT_M6="암호학 및 암호화"
        CT_M7="패스워드 보안 및 크래킹"
        CT_M8="사회공학적 인식"
        CT_M9="네트워크 보안 및 방화벽"
        CT_M10="무선 보안"
        CT_M11="디지털 포렌식"
        CT_M12="악성코드 분석 기초"
        CT_M13="CTF 및 실습 과제"
        CT_M14="도구 및 완전한 치트시트"
        CT_M15="보고서 및 학습 진행"
        CT_M16="트레이닝 아레나 - 레벨별 실습"
        CT_M17="미션 시스템 - 실제 펜테스트 시뮬레이션 작업"
        CT_M0="종료"
        CT_MPROMPT="메뉴 선택 [0-17]: "
        CT_LANG_MENU="언어 변경"
        CT_CORRECT="정답"
        CT_WRONG="오답"
        CT_HINT="힌트"
        CT_INFO="정보"
        CT_NOTE="참고"
        CT_VERIFY="확인"
        CT_SUCCESS="성공"
        CT_FAIL="실패"
        CT_SCORE="점수"
        CT_PASSED="합격"
        CT_NOT_PASSED="불합격 - 자료를 다시 학습하세요"
        CT_ENOUGH="보통 - 더 나은 결과를 위해 반복하세요"
        CT_Q="질문"
        CT_ANS="답변"
        CT_LVL_NB="초보자"
        CT_LVL_INT="중급"
        CT_LVL_ADV="고급"
        CT_LVL_EXP="전문가"
        CT_ARENA_HDR="CYBERTUZ - 트레이닝 아레나"
        CT_MISSION_HDR="CYBERTUZ - 활성 미션"
        CT_MISSION_MENU="CYBERTUZ - 미션 시스템"
        CT_MISSION_STATUS="모든 미션 상태"
        CT_DONE="완료"
        CT_PENDING="미완료"
        CT_LV_PROMPT="레벨 선택 [0-8]: "
        CT_MS_PROMPT="미션 선택 [0-7]: "
        CT_PROGRESS="진행"
        CT_BACKGROUND="배경"
        CT_OBJECTIVE="미션 목표"
        CT_EXEC="실행"
        CT_ANALYSIS="분석"
        CT_RESULT="결과"
        CT_SAVED="언어가 저장되었습니다."
        CT_SESSION="세션 시작"
        CT_EASY="쉬움"
        CT_MEDIUM="보통"
        CT_HARD="어려움"
        CT_LEVEL="레벨"
        CT_PRACTICE="실습"
        CT_SCENARIO="시나리오"
        CT_TARGET="대상"
        CT_FINDING="발견"
        ;;

    esac

    export CYBERTUZ_LANG CT_LANG_NAME
    export CT_SUBTITLE CT_FOR_EDU CT_DISC_TITLE CT_DISC_1 CT_DISC_2
    export CT_DISC_RULES CT_RULE_1 CT_RULE_2 CT_RULE_3 CT_RULE_4
    export CT_WARN CT_AGREE_Q CT_AGREE_OK CT_EXIT CT_INVALID CT_ENTER CT_BACK
    export CT_MENU_HDR CT_M1 CT_M2 CT_M3 CT_M4 CT_M5 CT_M6 CT_M7 CT_M8
    export CT_M9 CT_M10 CT_M11 CT_M12 CT_M13 CT_M14 CT_M15 CT_M16 CT_M17 CT_M0
    export CT_MPROMPT CT_LANG_MENU
    export CT_CORRECT CT_WRONG CT_HINT CT_INFO CT_NOTE CT_VERIFY
    export CT_SUCCESS CT_FAIL CT_SCORE CT_PASSED CT_NOT_PASSED CT_ENOUGH
    export CT_Q CT_ANS CT_LVL_NB CT_LVL_INT CT_LVL_ADV CT_LVL_EXP
    export CT_ARENA_HDR CT_MISSION_HDR CT_MISSION_MENU CT_MISSION_STATUS
    export CT_DONE CT_PENDING CT_LV_PROMPT CT_MS_PROMPT CT_PROGRESS
    export CT_BACKGROUND CT_OBJECTIVE CT_EXEC CT_ANALYSIS CT_RESULT
    export CT_SAVED CT_SESSION CT_EASY CT_MEDIUM CT_HARD CT_LEVEL
    export CT_PRACTICE CT_SCENARIO CT_TARGET CT_FINDING
}

ct_load_lang() {
    if [ -f "$LANG_SAVE_FILE" ]; then
        local saved
        saved=$(cat "$LANG_SAVE_FILE" 2>/dev/null | tr -d '[:space:]')
        if [ -n "$saved" ]; then
            _ct_set_lang "$saved"
            return 0
        fi
    fi
    return 1
}

ct_save_lang() {
    echo "$1" > "$LANG_SAVE_FILE"
}

ct_choose_language() {
    local R='\033[0;31m'
    local G='\033[0;32m'
    local Y='\033[1;33m'
    local C='\033[0;36m'
    local W='\033[1;37m'
    local D='\033[2m'
    local N='\033[0m'

    clear
    echo -e "${R}"
    echo "  ██████╗██╗   ██╗██████╗ ███████╗██████╗ ████████╗██╗   ██╗███████╗"
    echo " ██╔════╝╚██╗ ██╔╝██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██║   ██║╚══███╔╝"
    echo " ██║      ╚████╔╝ ██████╔╝█████╗  ██████╔╝   ██║   ██║   ██║  ███╔╝ "
    echo " ██║       ╚██╔╝  ██╔══██╗██╔══╝  ██╔══██╗   ██║   ██║   ██║ ███╔╝  "
    echo " ╚██████╗   ██║   ██████╔╝███████╗██║  ██║   ██║   ╚██████╔╝███████╗"
    echo "  ╚═════╝   ╚═╝   ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚══════╝"
    echo -e "${N}"
    echo -e "${C}  =================================================================${N}"
    echo -e "${W}  CyberTuz is a comprehensive cyber security learning platform.${N}"
    echo -e "${D}  It covers ethical hacking, penetration testing, network security,${N}"
    echo -e "${D}  web app security, cryptography, CTF challenges, digital forensics,${N}"
    echo -e "${D}  and real pentest simulations. Built for Termux on Android.${N}"
    echo -e "${D}  All content is strictly for educational purposes only.${N}"
    echo -e "${C}  =================================================================${N}"
    echo ""
    echo -e "${Y}  Select your language:${N}"
    echo ""
    echo -e "  ${G}[1]${N}   English"
    echo -e "  ${G}[2]${N}   Indonesia"
    echo -e "  ${G}[3]${N}   हिन्दी          (Hindi / India)"
    echo -e "  ${G}[4]${N}   Bahasa Melayu   (Malaysia)"
    echo -e "  ${G}[5]${N}   Русский         (Russian)"
    echo -e "  ${G}[6]${N}   中文 简体        (Chinese Simplified / Mandarin)"
    echo -e "  ${G}[7]${N}   日本語           (Japanese)"
    echo -e "  ${G}[8]${N}   ภาษาไทย         (Thai)"
    echo -e "  ${G}[9]${N}   Tieng Viet      (Vietnamese)"
    echo -e "  ${G}[10]${N}  العربية          (Arabic)"
    echo -e "  ${G}[11]${N}  Español         (Spanish)"
    echo -e "  ${G}[12]${N}  Italiano        (Italian)"
    echo -e "  ${G}[13]${N}  한국어           (Korean)"
    echo ""
    echo -e "${C}  =================================================================${N}"
    echo -ne "  ${W}Your choice [1-13]: ${N}"
    read -r _ch

    local _sel="en"
    case "$_ch" in
        1)  _sel="en" ;;
        2)  _sel="id" ;;
        3)  _sel="hi" ;;
        4)  _sel="ms" ;;
        5)  _sel="ru" ;;
        6)  _sel="zh" ;;
        7)  _sel="ja" ;;
        8)  _sel="th" ;;
        9)  _sel="vi" ;;
        10) _sel="ar" ;;
        11) _sel="es" ;;
        12) _sel="it" ;;
        13) _sel="ko" ;;
        *)  _sel="en" ;;
    esac

    _ct_set_lang "$_sel"
    ct_save_lang "$_sel"

    clear
    echo -e "${R}"
    echo "  ██████╗██╗   ██╗██████╗ ███████╗██████╗ ████████╗██╗   ██╗███████╗"
    echo " ██╔════╝╚██╗ ██╔╝██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██║   ██║╚══███╔╝"
    echo " ██║      ╚████╔╝ ██████╔╝█████╗  ██████╔╝   ██║   ██║   ██║  ███╔╝ "
    echo " ██║       ╚██╔╝  ██╔══██╗██╔══╝  ██╔══██╗   ██║   ██║   ██║ ███╔╝  "
    echo " ╚██████╗   ██║   ██████╔╝███████╗██║  ██║   ██║   ╚██████╔╝███████╗"
    echo "  ╚═════╝   ╚═╝   ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚══════╝"
    echo -e "${N}"
    echo -e "${C}  =================================================================${N}"
    echo -e "  ${W}Language / Bahasa : ${G}${CT_LANG_NAME}${N}"
    echo -e "  ${G}${CT_SAVED}${N}"
    echo -e "${C}  =================================================================${N}"
    echo ""
    sleep 1
}
