#!/bin/bash
# =============================================================================
#   CyberTuz Installer
#   Installs cybertuz command globally so you can run it from anywhere
# =============================================================================

RED='\033[0;31m'
GREEN='\033[0;32m'
YELLOW='\033[1;33m'
CYAN='\033[0;36m'
WHITE='\033[1;37m'
DIM='\033[2m'
BOLD='\033[1m'
RESET='\033[0m'

INSTALL_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CYBERTUZ_MAIN="$INSTALL_DIR/cybertuz.sh"

detect_env() {
    if [ -d "/data/data/com.termux" ] || [ -n "$TERMUX_VERSION" ]; then
        ENV_TYPE="termux"
        BIN_DIR="$PREFIX/bin"
        DATA_DIR="$HOME/.cybertuz"
    elif [ "$(uname -s)" = "Darwin" ]; then
        ENV_TYPE="macos"
        BIN_DIR="/usr/local/bin"
        DATA_DIR="$HOME/.cybertuz"
    else
        ENV_TYPE="linux"
        if [ -w "/usr/local/bin" ]; then
            BIN_DIR="/usr/local/bin"
        else
            BIN_DIR="$HOME/.local/bin"
        fi
        DATA_DIR="$HOME/.cybertuz"
    fi
}

print_banner() {
    clear
    echo -e "${RED}"
    echo "  ██████╗██╗   ██╗██████╗ ███████╗██████╗ ████████╗██╗   ██╗███████╗"
    echo " ██╔════╝╚██╗ ██╔╝██╔══██╗██╔════╝██╔══██╗╚══██╔══╝██║   ██║╚══███╔╝"
    echo " ██║      ╚████╔╝ ██████╔╝█████╗  ██████╔╝   ██║   ██║   ██║  ███╔╝ "
    echo " ██║       ╚██╔╝  ██╔══██╗██╔══╝  ██╔══██╗   ██║   ██║   ██║ ███╔╝  "
    echo " ╚██████╗   ██║   ██████╔╝███████╗██║  ██║   ██║   ╚██████╔╝███████╗"
    echo "  ╚═════╝   ╚═╝   ╚═════╝ ╚══════╝╚═╝  ╚═╝   ╚═╝    ╚═════╝ ╚══════╝"
    echo -e "${RESET}"
    echo -e "${CYAN}  =================================================================${RESET}"
    echo -e "${WHITE}${BOLD}              CyberTuz Installer${RESET}"
    echo -e "${DIM}        Comprehensive Cyber Security Learning Platform${RESET}"
    echo -e "${CYAN}  =================================================================${RESET}"
    echo ""
}

check_deps() {
    echo -e "${CYAN}[*]${RESET} Checking dependencies..."
    local missing=()

    command -v bash >/dev/null 2>&1 || missing+=("bash")

    # Optional but recommended
    local optional_missing=()
    command -v nmap   >/dev/null 2>&1 || optional_missing+=("nmap")
    command -v curl   >/dev/null 2>&1 || optional_missing+=("curl")
    command -v python3 >/dev/null 2>&1 || optional_missing+=("python3")
    command -v dig    >/dev/null 2>&1 || optional_missing+=("dig (dnsutils)")
    command -v whois  >/dev/null 2>&1 || optional_missing+=("whois")

    if [ ${#missing[@]} -gt 0 ]; then
        echo -e "${RED}[✗]${RESET} Required but missing: ${missing[*]}"
        exit 1
    fi

    echo -e "${GREEN}[✓]${RESET} Required dependencies: OK"

    if [ ${#optional_missing[@]} -gt 0 ]; then
        echo -e "${YELLOW}[!]${RESET} Optional tools not installed: ${optional_missing[*]}"
        if [ "$ENV_TYPE" = "termux" ]; then
            echo -e "${DIM}    Install with: pkg install nmap curl dnsutils whois python3${RESET}"
        elif [ "$ENV_TYPE" = "linux" ]; then
            echo -e "${DIM}    Install with: sudo apt install nmap curl dnsutils whois python3${RESET}"
        fi
    else
        echo -e "${GREEN}[✓]${RESET} All optional tools: OK"
    fi
    echo ""
}

do_install() {
    echo -e "${CYAN}[*]${RESET} Installing CyberTuz..."

    if [ ! -f "$CYBERTUZ_MAIN" ]; then
        echo -e "${RED}[✗]${RESET} cybertuz.sh not found in: $INSTALL_DIR"
        echo -e "${RED}    Run this installer from inside the cybertuz directory.${RESET}"
        exit 1
    fi

    chmod +x "$CYBERTUZ_MAIN"
    chmod +x "$INSTALL_DIR/lang.sh"
    chmod +x "$INSTALL_DIR/modules/"*.sh 2>/dev/null

    mkdir -p "$DATA_DIR/logs" "$DATA_DIR/reports"

    mkdir -p "$BIN_DIR"

    LAUNCHER="$BIN_DIR/cybertuz"
    cat > "$LAUNCHER" << LAUNCHER_EOF
#!/bin/bash
# CyberTuz launcher - generated by install.sh
exec bash "$INSTALL_DIR/cybertuz.sh" "\$@"
LAUNCHER_EOF

    chmod +x "$LAUNCHER"

    if ! echo "$PATH" | grep -q "$BIN_DIR"; then
        echo -e "${YELLOW}[!]${RESET} ${BIN_DIR} is not in your PATH."

        SHELL_CFG=""
        if [ -f "$HOME/.bashrc" ];  then SHELL_CFG="$HOME/.bashrc"; fi
        if [ -f "$HOME/.zshrc" ];   then SHELL_CFG="$HOME/.zshrc"; fi
        if [ "$ENV_TYPE" = "termux" ] && [ -f "$HOME/.bashrc" ]; then
            SHELL_CFG="$HOME/.bashrc"
        fi

        if [ -n "$SHELL_CFG" ]; then
            if ! grep -q "$BIN_DIR" "$SHELL_CFG"; then
                echo "" >> "$SHELL_CFG"
                echo "# CyberTuz" >> "$SHELL_CFG"
                echo "export PATH=\"$BIN_DIR:\$PATH\"" >> "$SHELL_CFG"
                echo -e "${GREEN}[✓]${RESET} Added ${BIN_DIR} to PATH in ${SHELL_CFG}"
                echo -e "${YELLOW}    Run: source ${SHELL_CFG}${RESET}"
            fi
        else
            echo -e "${YELLOW}    Manually add to your shell config:${RESET}"
            echo -e "${DIM}    export PATH=\"$BIN_DIR:\$PATH\"${RESET}"
        fi
    fi

    echo ""
    echo -e "${GREEN}  =================================================================${RESET}"
    echo -e "${GREEN}${BOLD}  [✓] CyberTuz installed successfully!${RESET}"
    echo -e "${GREEN}  =================================================================${RESET}"
    echo ""
    echo -e "${WHITE}  Installed to : ${CYAN}$LAUNCHER${RESET}"
    echo -e "${WHITE}  Data dir     : ${CYAN}$DATA_DIR${RESET}"
    echo -e "${WHITE}  Source       : ${CYAN}$INSTALL_DIR${RESET}"
    echo ""
    echo -e "${YELLOW}  How to run:${RESET}"
    echo -e "${WHITE}    cybertuz${RESET}"
    echo ""
    echo -e "${DIM}  To uninstall: bash $INSTALL_DIR/install.sh --uninstall${RESET}"
    echo ""
}

do_uninstall() {
    echo -e "${CYAN}[*]${RESET} Uninstalling CyberTuz..."

    LAUNCHER="$BIN_DIR/cybertuz"
    if [ -f "$LAUNCHER" ]; then
        rm -f "$LAUNCHER"
        echo -e "${GREEN}[✓]${RESET} Removed: $LAUNCHER"
    else
        echo -e "${YELLOW}[!]${RESET} Launcher not found at: $LAUNCHER"
    fi

    echo ""
    echo -e "${GREEN}[✓]${RESET} CyberTuz uninstalled."
    echo -e "${DIM}    Your data in $DATA_DIR was kept. Remove manually if desired.${RESET}"
    echo ""
}

main() {
    detect_env
    print_banner

    echo -e "${DIM}  Environment : $ENV_TYPE${RESET}"
    echo -e "${DIM}  Install dir : $INSTALL_DIR${RESET}"
    echo -e "${DIM}  Bin dir     : $BIN_DIR${RESET}"
    echo ""

    case "${1:-}" in
        --uninstall|-u)
            do_uninstall
            ;;
        --check|-c)
            check_deps
            ;;
        --help|-h)
            echo "Usage: bash install.sh [option]"
            echo ""
            echo "  (no option)    Install cybertuz"
            echo "  --uninstall    Remove cybertuz from system"
            echo "  --check        Check dependencies only"
            echo "  --help         Show this help"
            echo ""
            ;;
        *)
            check_deps
            do_install
            ;;
    esac
}

main "$@"
